charts/rstudio/templates/deployment.yml
charts/rstudio/values.yaml

* Supply key for encrypting secure cookies
* Change healthcheck URL to `/` as `/health-check` is a Pro feature

Enable deploying opensource Rstudio

---

charts/elasticsearch-curator/Chart.yaml
charts/nfs-migration/Chart.yaml
charts/shiny-app/Chart.yaml

Reverts ministryofjustice/analytics-platform-helm-charts#9

Revert "Deprecate unnecessary charts"

---

charts/elasticsearch-curator/Chart.yaml
charts/nfs-migration/Chart.yaml
charts/shiny-app/Chart.yaml

Reverts ministryofjustice/analytics-platform-helm-charts#10

Revert "Revert "Deprecate unnecessary charts""

---

charts/cpfrontend/Chart.yaml
charts/cpfrontend/templates/deployment.yaml

This missing var is causing frontend deployments to fail

Add missing AUTH0_CALLBACK_URL env var

---

charts/cpanel/CHANGELOG.md
charts/cpanel/Chart.yaml
charts/cpanel/README.md
charts/cpanel/templates/deployment.yaml
charts/cpanel/templates/secrets.yaml
charts/cpanel/values.yaml

Add NFS_HOSTNAME to cpanel

---

charts/cpfrontend/Chart.yaml
charts/cpfrontend/templates/deployment.yaml
charts/cpfrontend/values.yaml

Missing env var prevents frontend from calling API

Add API_URL env var to cpfrontend

---

charts/cpanel/README.md

...to force build or charts index

cpanel: Updated README with RStudio deploy variables

---

charts/init-user/templates/role-binding.yml

The built-in admin role is cluster role

admin is a cluster role

---

charts/README.md
charts/kube2iam/CHANGELOG.md
charts/kube2iam/Chart.yaml
charts/kube2iam/templates/cluster-role-binding.yml
charts/kube2iam/templates/cluster-role.yml
charts/kube2iam/templates/daemonset.yml
charts/kube2iam/templates/service-account.yml

k8s resources copied from https://github.com/jtblin/kube2iam/pull/99

kube2iam v1.0.0: Added Service account, to make it work when RBAC enabled

---

charts/README.md

[Ticket](https://trello.com/c/1Ced1fHi)

Docs for installing Prometheus Operator

---

charts/idler/Chart.yaml
charts/idler/templates/cronjob.yaml
charts/idler/values.yaml

* Run idler script as a cron job (default every night at 10pm)

Add idler chart

---

charts/fluentd/values.yaml

Trello: https://trello.com/c/xPw9p8mF
Making changes to satisfy deprecations warnings.
FluentD Version: 1.0.1
Fluent-Plugin_ElasticSearch: 2.4.1

FIX:  FluentD

---

charts/fluentd/templates/clusterrole.yaml
charts/fluentd/templates/clusterrolebinding.yaml
charts/fluentd/templates/daemonset.yaml
charts/fluentd/templates/serviceaccount.yaml

Trello: https://trello.com/c/w9vZrvgw
Adding RBAC manifests to create/configure:
* Service Account
* Role
* Role Binding
Binding service account to FluentD `DeamonSet`

RBAC: FluentD

---

charts/init-user/templates/resource-quota.yml

__Nice to have but non-essential in my opinion__
Trello: https://trello.com/c/6lSG3iOi
Adding namespace scoped Resource Quota for PVCs

Init User Resource Quota

---

charts/jupyter-lab/templates/deployment.yaml
charts/jupyter-lab/values.yaml

I forgot to modify the volume mount to match the PVC
Explicitly defining image version.

Volume Mount

---

charts/cpfrontend/templates/deployment.yaml
charts/cpfrontend/templates/service-account.yaml

Provisions a service account to run the pod resources
Helps with auditing.
Trello: https://trello.com/c/pT8lrFNu

Control Panel Frontend Service Account

---

charts/jupyter-lab/values.yaml

Use latest auth proxy release.

Auth Proxy Tag

---

charts/idler/CHANGELOG.md
charts/idler/Chart.yaml
charts/idler/README.md
charts/idler/templates/clusterrole.yaml
charts/idler/templates/cronjob.yaml
charts/idler/values.yaml

* Give idler access to metrics API
* Add env var for CPU usage threshold to prevent idling

Idler checks RStudio CPU usage before idling

---

charts/kubernetes-dashboard/CHANGELOG.md
charts/kubernetes-dashboard/Chart.yaml
charts/kubernetes-dashboard/README.md
charts/kubernetes-dashboard/templates/cluster-role.yaml
charts/kubernetes-dashboard/templates/cluster-rolebinding.yaml
charts/kubernetes-dashboard/templates/deployment.yaml
charts/kubernetes-dashboard/templates/ingress.yaml
charts/kubernetes-dashboard/templates/secrets.yaml
charts/kubernetes-dashboard/templates/service-account.yaml
charts/kubernetes-dashboard/templates/service.yaml
charts/kubernetes-dashboard/values.yaml

Chart representation of [kubernetes-dashboard](https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml) with read only access by default

Kubernetes Dashboard: Initial Commit

---

charts/init-user/Chart.yaml

This is to trigger a rebuild of the tarball and update the repo.

Incrementing Chart Version

---

charts/jupyter-lab/templates/secrets.yaml

Fixing auth proxy callback envvar to point to the correct endpoint.

Jupyter Auth0 CallBack URL

---

charts/jupyter-lab/templates/secrets.yaml

Reverts ministryofjustice/analytics-platform-helm-charts#132

Revert "Jupyter Auth0 CallBack URL"

---

charts/fluentd/templates/clusterrolebinding.yaml

Modifying role reference from core API to rbac.authorization.k8s.io

Cluster Role API Group

---

charts/jupyter-lab/README.md

URL is based on chart name so amending to suit.

Amending Docs

---

charts/fluentd/CHANGELOG.md
charts/fluentd/Chart.yaml

Bumped chart version
Added CHANGELOG

Bump FluentD Chart

---

charts/concourse-org-pipeline/CHANGELOG.md
charts/concourse-org-pipeline/Chart.yaml
charts/concourse-org-pipeline/README.md
charts/concourse-org-pipeline/templates/secrets.yaml
charts/concourse-org-pipeline/values.yaml

* Adds secrets for the IP ranges that we can restrict webapp access to
* Added README and CHANGELOG

Add secrets and update pipeline for deployment params

---

charts/rstudio/CHANGELOG.md
charts/rstudio/Chart.yaml
charts/rstudio/values.yaml

Modified RStudio image tag to point to most recent image
Minor version point release increment

RStudio-Image

---

charts/cpanelapi-pipeline/Chart.yaml
charts/cpanelapi-pipeline/files/pipeline.yaml
charts/cpanelapi-pipeline/files/set-pipeline.sh
charts/cpanelapi-pipeline/templates/configmap.yaml
charts/cpanelapi-pipeline/templates/job.yaml
charts/cpanelapi-pipeline/templates/secrets.yaml
charts/cpanelapi-pipeline/values.yaml

* New helm chart for Concourse pipeline that deploys Control Panel API

Add chart for Control Panel API deployment pipeline

---

charts/concourse-org-pipeline/CHANGELOG.md
charts/concourse-org-pipeline/Chart.yaml
charts/concourse-org-pipeline/templates/secrets.yaml
charts/concourse-org-pipeline/values.yaml

* Add Control Panel API credentials so that pipeline task can access the API to get an app's IAM role name

Add cpanel API credentials

---

charts/cpanel/templates/deployment.yaml

Broke the deployment by removing quotes from something

Fix quoting

---

charts/README.md

Updated readme to reflect new CI

Concourse Install

---

charts/logstash/.helmignore
charts/logstash/CHANGELOG.md
charts/logstash/Chart.yaml
charts/logstash/README.md
charts/logstash/files/http.conf
charts/logstash/templates/_helpers.tpl
charts/logstash/templates/configmap.yaml
charts/logstash/templates/deployment.yaml
charts/logstash/templates/ingress.yaml
charts/logstash/templates/secrets.yaml
charts/logstash/templates/service-account.yaml
charts/logstash/templates/service.yaml
charts/logstash/values.yaml

Deploys logstash with preconfigured http input, output to elasticsearch and x-pack
monitoring.

Logstash Chart

---

charts/webapp/CHANGELOG.md
charts/webapp/Chart.yaml
charts/webapp/templates/deployment.yaml
charts/webapp/templates/service-account.yaml

Applying best practice by adding a service account.  No operational
change.

WebApp: Service Account

---

charts/webapp/migrations/concourse_mod_helm_repo.sh

Updates the url of the helm repo but really serves as an example for
modifying existing pipelines in concousre.

Update Helm Repo

---

charts/logstash/CHANGELOG.md
charts/logstash/Chart.yaml
charts/logstash/values.yaml

Changing image tag to match elasticsearch version

Upgrade Logstash

---

charts/jupyter-lab/values.yaml

Updating the image to the latest version

Update Jupyter Image Tag

---

charts/jupyter-lab/CHANGELOG.md
charts/jupyter-lab/Chart.yaml

Forgot to update changelog in [PR](https://github.com/ministryofjustice/analytics-platform-helm-charts/pull/192)

Updating Jupyter Changelog

---

charts/rbac/.helmignore
charts/rbac/CHANGELOG.md
charts/rbac/Chart.yaml
charts/rbac/README.md
charts/rbac/templates/_helpers.tpl
charts/rbac/templates/app-support.yaml
charts/rbac/templates/cluster-admins.yaml
charts/rbac/values.yaml

Initial commit
A chart to deploy miscellaneous `rbac` resources for users (mainly)
[Trello](https://trello.com/c/ZK7eHGqB)

Helm: RBAC Chart

---

charts/jupyter-lab/CHANGELOG.md
charts/jupyter-lab/Chart.yaml
charts/jupyter-lab/values.yaml
charts/webapp/CHANGELOG.md
charts/webapp/Chart.yaml
charts/webapp/values.yaml

* Picks up the fix for the login loop problem
See [Trello #938](https://trello.com/c/yeeBL0Kz)

Use latest auth-proxy for webapps and jupyter

---

charts/rbac/CHANGELOG.md
charts/rbac/Chart.yaml
charts/rbac/README.md
charts/rbac/templates/airflow-support.yaml
charts/rbac/values.yaml

See [Trello](https://trello.com/c/Tq1xQCf3)
Created `Rolebinding` for airflow support that binds to __app-support__ `Clusterrole`.

RBAC: Airflow Support

---

charts/airflow-k8s/templates/hooks/init-airflow-ns-hook.yml

Use service account from helm values instead of hard-coding

Airflow: Chart fix - service account

---

charts/unidler/Chart.yaml
charts/unidler/templates/clusterrole.yaml

The unidler needs to read its own ingress.

Add permission to read ingress to unidler

---

charts/airflow-k8s/CHANGELOG.md
charts/airflow-k8s/Chart.yaml
charts/airflow-k8s/templates/_env.yml
charts/airflow-k8s/templates/configmap.yml
charts/airflow-k8s/templates/secrets.yml
charts/airflow-k8s/values.yaml

Added `airflow.config.smtp.*` values/settings.

airflow-k8s 0.0.4: Configuration for SMTP

---

charts/cert-manager-resources/CHANGELOG.md
charts/cert-manager-resources/Chart.yaml
charts/cert-manager-resources/README.md
charts/cert-manager-resources/templates/_helpers.tpl
charts/cert-manager-resources/templates/certificate.yaml
charts/cert-manager-resources/templates/cluster-issuer.yaml
charts/cert-manager-resources/values.yaml

[Trello](https://trello.com/c/M1snktNZ)
Initial commit
- Provisions a [cluster-issuer](https://cert-manager.readthedocs.io/en/latest/reference/clusterissuers.html) resource
- This resource defines the request to the CA and any validation challenges   
- Provisions a [certificate](https://cert-manager.readthedocs.io/en/latest/reference/certificates.html) resource
- This resource defines the tls cert 
Relates to [PR](https://github.com/ministryofjustice/analytics-platform-config/pull/76)

Cert-Manager Resources

---

charts/cpanel/templates/job.yaml

Because the migration is now not done in Dockerfile startup. See: https://github.com/ministryofjustice/analytics-platform-control-panel/pull/335

Add job for the controlpanel migration

---

charts/unidler/CHANGELOG.md
charts/unidler/Chart.yaml
charts/unidler/templates/deployment.yaml
charts/unidler/templates/ingress.yaml
charts/unidler/values.yaml

Default ingress class is now `istio` (was `nginx`)

Unidler v1.0.0: Configurable ingress class and fix unidling with Istio

---

README.md

So that's it's easy to get there when you're not familiar with how things work.

Link to Concourse pipeline which updates helm repo

---

charts/cert-manager-resources/README.md

A few minor suggestions, based on my experience of a fresh deploy

Cert manager tweaks

---

charts/cpanel/CHANGELOG.md
charts/cpanel/Chart.yaml
charts/cpanel/templates/secrets.yaml

Adds the secrets to the secrets file so that the pods can access the jupyter
lab secrets

Control Panel v1.1.1: Support Jupyter [bugfix]

---

charts/websocket-status/.helmignore
charts/websocket-status/Chart.yaml
charts/websocket-status/templates/_helpers.tpl
charts/websocket-status/templates/deployment.yaml
charts/websocket-status/templates/ingress.yaml
charts/websocket-status/templates/service.yaml
charts/websocket-status/values.yaml

Initial commit of the websocket status page chart. It's quite a simple one as it
needs no configuration.

Websocket Status: 0.1.0

---

charts/jupyter-lab/README.md
charts/rstudio/README.md

username/password login as a distraction to the github login option

Tell auth0 not to offer a username/password login

---

charts/jupyter-lab/CHANGELOG.md

See: [PR](https://github.com/ministryofjustice/analytics-platform-helm-charts/pull/248)

Amend changelog

---

charts/cluster-autoscaler/README.md

Forgot to add documentation `PodDisruptionBudgets`

Cluster AutoScaler docs

---

charts/airflow-k8s/templates/ingress.yml
charts/aws-login/templates/ingress.yaml
charts/cpanel/templates/ingress.yaml
charts/cpfrontend/templates/ingress.yaml
charts/hubot/templates/ingress.yaml
charts/jupyter-lab/templates/ingress.yaml
charts/kibana-auth-proxy/templates/ingress.yaml
charts/kubernetes-dashboard/templates/ingress.yaml
charts/logstash/templates/ingress.yaml
charts/rstudio/templates/ingress.yml
charts/shiny-app/templates/ingress.yaml
charts/unidler/templates/ingress.yaml

Remove path from all the ingresses, to match whats deployed to alpha

---

charts/fluentd/CHANGELOG.md
charts/fluentd/Chart.yaml
charts/fluentd/values.yaml
charts/webapp/CHANGELOG.md
charts/webapp/Chart.yaml
charts/webapp/values.yaml

After increasing alerting we witnessed alerts that throttling on fluentd
instances are high.
- Increased cpu shares for fluentd

FluentD Resources

---

charts/cluster-autoscaler/CHANGELOG.md
charts/cluster-autoscaler/Chart.yaml
charts/cluster-autoscaler/values.yaml

Alerting reports high throttling.  Increasing CPU shares.

Cluster AutoScaler CPU

---

charts/fluentd/CHANGELOG.md
charts/fluentd/Chart.yaml
charts/fluentd/templates/daemonset.yaml
charts/fluentd/values.yaml

- Changed `priorityclassname` key to `priorityClassName`

FluentD Pod Priority Class 2

---

charts/prometheus-resources/CHANGELOG.md
charts/prometheus-resources/Chart.yaml
charts/prometheus-resources/values.yaml

- Removed duplicate alerting rules
- Modified custom alerts to display message field like operator alerts

Prometheus Analytical Rules

---

charts/rbac/README.md

Make Configuration Table descriptions more helpful
- Expanded descriptions
- Added `Scope` Column

Make README More Helpful

---

charts/concourse-org-pipeline/CHANGELOG.md
charts/concourse-org-pipeline/Chart.yaml
charts/concourse-org-pipeline/values.yaml
charts/webhook-dispatcher/Chart.yaml
charts/webhook-dispatcher/values.yaml

Updates org resource:
- adds tests pipeline for dag repos and lookup repos
- adds pull-request resource to concourse task
Updates webgook dispatcher:
- check pull-request resource on push event from githiub

Update org scanner and webhook dispatcher versions

---

charts/rstudio/CHANGELOG.md
charts/rstudio/Chart.yaml
charts/rstudio/values.yaml

New image startup script, refactored to be more robust against bad conda create of the rstudio
environment.

Rstudio: bump image version

---

charts/airflow-k8s/CHANGELOG.md
charts/airflow-k8s/Chart.yaml
charts/airflow-k8s/values.yaml
charts/airflow-sqlite/CHANGELOG.md
charts/airflow-sqlite/Chart.yaml
charts/airflow-sqlite/values.yaml

- Dockerfile changes: https://github.com/ministryofjustice/analytics-platform-airflow-docker-image/pull/5
- Airflow Changelog: https://github.com/apache/airflow/blob/master/CHANGELOG.txt

Bumped Airflow to 1.10.3 in airflow-(k8s|sqlite)

---

charts/concourse-org-pipeline/templates/secrets.yaml

Config value added in https://github.com/ministryofjustice/analytics-platform-config/pull/153

Add secret - Moj digital network IP

---

charts/init-user/CHANGELOG.md
charts/init-user/Chart.yaml
charts/init-user/templates/role-binding.yml

Allow members of the user-support github team to have admin access to
user namespaces

User Support

---

charts/fluentd/CHANGELOG.md
charts/fluentd/Chart.yaml
charts/fluentd/templates/daemonset.yaml

* Added selector to daemonset spec as required by the K8s apps/v1 api

add selector to daemonset spec

---

charts/webapp/CHANGELOG.md
charts/webapp/Chart.yaml
charts/webapp/templates/deployment.yaml

Big fix for failing to deploy: https://concourse.services.alpha.mojanalytics.xyz/teams/main/pipelines/civ-dis-dashboard/jobs/deploy/builds/4

Bugfix webapp matchselector

---

charts/nfs-backup/Chart.yaml
charts/nfs-backup/README.md

Amending command in  docs to include helm repo
relates to [PR](https://github.com/ministryofjustice/analytical-platform-infrastructure/pull/42)
**Deployed**

Home Directory NFS Backups

---

charts/init-platform/CHANGELOG.md
charts/init-platform/Chart.yaml
charts/init-platform/templates/create-nfs-dir-job.yml
charts/init-platform/templates/efs-pv.yml

Modifying to work with serjNAS
- Modified expected mount from `/users/homes` to `/users/home`
- Modified working directory from `/tmp/home` to `/tmp`
__Deployed__

New Env Init Platform

---

charts/cpanel/CHANGELOG.md
charts/cpanel/Chart.yaml
charts/cpanel/values.yaml

Add `SLACK_API_TOKEN` and `SLACK_CHANNEL` environment variables

Add Slack environment variables

---

README.md

This commit lists the helm charts required for a full install rather than a
minimal install of the cluster

README: Add list of all charts required for full install

---

charts/config-user/Chart.yaml

bump version

---

charts/config-user/Chart.yaml
charts/config-user/files/git-config.sh

need to set git templates as 1001 user 
a) need to switch user first 
b) execute command

need to set git templates as 1001 user

---

charts/config-user/Chart.yaml
charts/config-user/files/git-config.sh

Revert back the git user to jovyan

revert back to jovyan user

---

charts/rstudio/CHANGELOG.md
charts/rstudio/Chart.yaml
charts/rstudio/values.yaml

Update r-studio tag to conda-6

update rstudio release tag

---

charts/rstudio/README.md

Add instruction for upgrading/downgrading R Studio to a helm chart version in the mojanalytics helm repo

Update rstudio docs

---

charts/webapp/CHANGELOG.md
charts/webapp/Chart.yaml
charts/webapp/values.yaml

Update version of auth-proxy to 5.2.5

---

charts/reset-user-home/.helmignore
charts/reset-user-home/Chart.yaml
charts/reset-user-home/templates/NOTES.txt
charts/reset-user-home/templates/_helpers.tpl
charts/reset-user-home/templates/deployment.yaml
charts/reset-user-home/templates/tests/test-connection.yaml
charts/reset-user-home/values.yaml

https://trello.com/c/CxKqlUpN/654-ripley-button-resets-a-users-conda-environment-etc

Add reset user home chart

---

charts/reset-user-home/Chart.yaml

Do nothing except increment the chart version as I forgot in the previous commit.

Incremenet the chart version as I forgot.

---

charts/reset-user-home/Chart.yaml
charts/reset-user-home/templates/_helpers.tpl
charts/reset-user-home/templates/deployment.yaml

The correct way to do this is probably have a hook to delete the job
after it completes, per this:
https://github.com/helm/helm/issues/1769
But it seems bugged in multiple versions of helm, so this workaround will do for the time being.

Append a 5 character random string to the job name.

---

charts/github-actions-runner/.helmignore
charts/github-actions-runner/Chart.yaml
charts/github-actions-runner/templates/_helpers.tpl
charts/github-actions-runner/templates/deployment.yaml
charts/github-actions-runner/templates/secret.yaml
charts/github-actions-runner/values.yaml

- Adds Helm Chart for GitHub Actions runner
- Adds example values.yaml
- Adds a deployment for the single container pod
- Adds a secret for the GitHub Organisation token

Add GitHub Actions runner chart

---

charts/github-actions-runner/Chart.yaml
charts/github-actions-runner/templates/deployment.yaml

This now uses the correct variable for labels

[github-actions-runner] Fix Helm telpate labels

---

charts/jupyter-lab/CHANGELOG.md
charts/jupyter-lab/Chart.yaml
charts/jupyter-lab/templates/deployment.yaml

Think this is everything needed for an update, but let me know if I missed anything.

Allow jupyter file viewer to see hidden files

---

charts/rstudio/CHANGELOG.md
charts/rstudio/Chart.yaml
charts/rstudio/templates/deployment.yml

[rstudio] Increase the initial delay on both the livenessProbe and

---

.github/ct.yaml
.github/workflows/charts-lint-test.yaml
charts/rstudio/CHANGELOG.md
charts/rstudio/Chart.yaml
charts/rstudio/values.yaml

- Adds Chart linting using CT
- Update the RStudio chart to trigger and pass linting 
- ANPL-226

[ANPL-226] Add chart testing

---

charts/rstudio/CHANGELOG.md
charts/rstudio/Chart.yaml
charts/rstudio/templates/deployment.yml

[rstudio] Change the default USER to rstudio

---

charts/rstudio/CHANGELOG.md
charts/rstudio/Chart.yaml
charts/rstudio/templates/configmap.yaml
charts/rstudio/templates/deployment.yml

We mount the config map as a script into the container and run it as
part of the container

[ANPL-239] Change the chown home command to a config map

---

charts/cpanel/Chart.yaml
charts/cpanel/templates/rbac-service-accounts.yaml
charts/cpanel/values.yaml

service account creation needs to be configurable to deploy cpanel in EKS

ANPL-402 Deploy Control panel helm chart to Dev EKS cluster with flux

---

charts/bootstrap-user/CHANGELOG.md
charts/bootstrap-user/Chart.yaml
charts/bootstrap-user/templates/_helpers.tpl
charts/bootstrap-user/templates/namespace-deploy-role.yaml
charts/bootstrap-user/templates/namespace.yml
charts/bootstrap-user/values.yaml

Add bootstrap user chart.
- Create user namespace
- Add Rolebinding to allow the control panel to deploy to it

ANPL-463 Add bootstrap user chart

---

charts/jupyter-lab/CHANGELOG.md
charts/jupyter-lab/Chart.yaml
charts/jupyter-lab/templates/deployment.yaml
charts/jupyter-lab/templates/service-account.yaml
charts/jupyter-lab/values.yaml

Add EKS IAM role annotations and EFS PVC for Jupyter lab

Add EKS annotations and EFS PVC for Jupyter lab

---

charts/jupyter-lab/CHANGELOG.md
charts/jupyter-lab/Chart.yaml
charts/jupyter-lab/templates/deployment.yaml

Correct the volume and claim name in Jupyter chart

Correct volume and claim name in Jupyter chart

---

charts/rstudio/CHANGELOG.md
charts/rstudio/Chart.yaml
charts/rstudio/templates/deployment.yml
charts/rstudio/templates/service-account.yaml
charts/rstudio/values.yaml

Add IRSA annotation to service account in RStudio chart 
Change RStudio deployment to use EFS Home PVC

Add IRSA annotation to RStudio chart and point to EFS Home PVC

---

charts/rstudio/CHANGELOG.md
charts/rstudio/Chart.yaml
charts/rstudio/templates/deployment.yml

Add username to deployment mount point for RStudio

Add username to deployment mount point for RStudio

---

charts/rstudio/CHANGELOG.md
charts/rstudio/Chart.yaml
charts/rstudio/templates/deployment.yml

Set init-container root to the same mount point as RStudio

Anpl 496 submount

---

charts/jupyter-lab/CHANGELOG.md
charts/jupyter-lab/Chart.yaml
charts/jupyter-lab/templates/deployment.yaml

Add username to subPath of EFS mount in Jupyterlab chart

ANPL-480 - Add username to subPath of EFS mount in Jupyterlab chart
