ministryofjustice/analytics-platform-helm-charts

- charts/kibana-auth-proxy/Chart.yaml
- charts/kibana-auth-proxy/templates/deployment.yaml
- charts/kibana-auth-proxy/templates/secrets.yml
- charts/kibana-auth-proxy/values.yaml
- no longer assumes that AWS ElasticSearch service is in use
- allows for differing Kibana credentials to be used based on identity provider used at login
See also chart config PR:
> Add support for vanilla Kibana installs

- charts/webapp/Chart.yaml
- charts/webapp/templates/deployment.yaml
- charts/webapp/templates/fluentd-configmap.yml
- charts/webapp/values.yaml
- ship logs to a separate logstash-apps-$ENV index
- ensure that logfiles are always read from the start or last-read position
- add time_nano field to allow Shiny app logs to be ordered correctly
- add hostname field to allow single set of logs to be viewed when app is deployed with replicas
> Updated webapp chart logging config

- charts/elasticsearch-curator/Chart.yaml
- charts/nfs-migration/Chart.yaml
- charts/shiny-app/Chart.yaml
Deprecating before removing:
* `elasticsearch-curator` - this is now a lambda function
* `nfs-migration` - this was a one off task
* `shiny-app` - superseded by `webapp`
> Deprecate unnecessary charts

- charts/webapp/CHANGELOG.md
- charts/webapp/Chart.yaml
- charts/webapp/README.md
- charts/webapp/templates/deployment.yaml
- charts/webapp/values.yaml
Ability to attach an IAM role to the app so that we can control the level
of permissions it has (e.g. access to S3 buckets, etc...)
The IAM role name is passed via the `AWS.IAMRole` chart value and it's
optional.
Under the hood the `iam.amazonaws.com/role` annotation is used by the
[kube2iam](https://github.com/jtblin/kube2iam) daemonset running in our kubernetes cluster.
- [AWS_IAM_ROLE param](https://github.com/moj-analytical-services/rshiny-template/pull/6) @ rshiny-template
- [request AWS_IAM_ROLE param](https://github.com/moj-analytical-services/webapp-template/pull/1) @ webapp-template
- [pass AWS_IAM_ROLE param to helm](https://github.com/ministryofjustice/analytics-platform-jenkins-lib/pull/18) @ jenkins-lib
https://trello.com/c/SrnUOD12/351-ability-for-webapps-to-assume-an-iam-rol …
> webapp: apps can assume an IAM role

- charts/cpanel/CHANGELOG.md
- charts/cpanel/Chart.yaml
- charts/cpanel/templates/deployment.yml
- charts/cpanel/values.yaml
This is so that the Control Panel API instances can have permissions to
perform certain operations (e.g. create S3 bucket, etc...)
https://trello.com/c/oNMQLEfF/360-add-iam-role-support-to-control-panel-api-helm-chart
- Role added: https://github.com/ministryofjustice/analytics-platform-ops/pull/106
- cpanel helm chart config: https://github.com/ministryofjustice/analytics-platform-config/pull/8
> cpanel: Control Panel API can assume an IAM role

- charts/cpanel/CHANGELOG.md
- charts/cpanel/Chart.yaml
- charts/cpanel/templates/deployment.yml
- charts/cpanel/values.yaml
This is required by: https://github.com/ministryofjustice/analytics-platform-control-panel/pull/19
See that PR for more info but basically it's how we tell the Control Panel
API the k8s worker role which will need to end up in the `sts:AssumeRole`
policy, used by kube2iam
https://trello.com/c/3dZNb9rw/379-cp-api-when-an-app-is-created-the-app-iam-role-is-created
> cpanel 3.0.0: Added K8S_WORKER_ROLE_ARN environment variable value

- charts/cpanel/CHANGELOG.md
- charts/cpanel/Chart.yaml
- charts/cpanel/templates/deployment.yml
- charts/cpanel/values.yaml
As suggested by Kerin in [other PR](https://github.com/ministryofjustice/analytics-platform-config/pull/10#pullrequestreview-63053919).
(I'm threating this as a non-breaking minor fix as the control_panel_api
code using this is not even merged yet, so just bumping the patch version number as bump the minor number seems overkill)
> cpanel: Renamed K8S_WORKER_ROLE_ARN => K8S_WORKER_ROLE_NAME

- charts/cpanel/CHANGELOG.md
- charts/cpanel/Chart.yaml
- charts/cpanel/README.md
- charts/cpanel/templates/deployment.yaml
- charts/cpanel/templates/secrets.yaml
- charts/cpanel/values.yaml
This is to pass the Sentry credentials to the control-panel-api: https://github.com/ministryofjustice/analytics-platform-control-panel/pull/34
https://trello.com/c/G8qny9WN/400-cp-api-set-up-sentry-for-exceptions
> cpanel: Added `SENTRY_DSN` environment variable value

- charts/webapp/Chart.yaml
- charts/webapp/templates/deployment.yaml
Prevents elasticsearch/kibana from filling up with not particularly useful logs.
Makes use of fluentd rule here https://github.com/ministryofjustice/analytics-platform-helm-charts/blob/master/charts/fluentd/values.yaml#L141
> webapp chart: Added missing ?healthz querystring param on healthchecks

- charts/rstudio/Chart.yaml
- charts/rstudio/templates/deployment.yml
- charts/rstudio/templates/ingress.yml
- charts/rstudio/templates/secrets.yml
- charts/rstudio/values.yaml
* Rename and restructure `values.yml` keys - helm best practice is to use camelCase for value names
* Add missing env vars for RStudio auth proxy
> Refactor to helm best practices and fix RStudio auth proxy env vars

- charts/cpfrontend/Chart.yaml
- charts/cpfrontend/values.yaml
This can be reverted when we switch to using git hashes for cpfrontend image tags instead of the branch name
> Make cpfrontend always pull the latest image

- charts/cpfrontend/Chart.yaml
- charts/cpfrontend/templates/deployment.yaml
It was confusingly named `api`
> Rename cpfrontend container

- charts/rstudio/Chart.yaml
- charts/rstudio/templates/deployment.yml
Added [maxUnavailable and maxSurge attributes](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#max-unavailable) to the RStudio Deployment spec, so that old pods are killed _after_ new pods are up and running.
To test:
1. Run `kubectl get pods -n user-$YOUR_USERNAME -w` to watch the status of your pods
2. In a separate terminal session, from the chart repo, run `helm upgrade $YOUR_USERNAME-rstudio ./charts/rstudio -f ../analytics-platform-config/chart-env-config/dev/rstudio.yml --set username=$YOUR_USERNAME --set aws.iamRole=dev_user_$YOUR_USERNAME --set rstudio.image.tag=latest --namespace user-$YOUR_USERNAME --install --wait` to update the Deployment
3. Watch the `kubectl get pods` output as the deployment rolls out, and verify that the old pod is not terminated …
> RStudio: ensure deployments are zero-downtime

- charts/nfs-backup/Chart.yaml
- charts/nfs-backup/templates/cronjob.yml
- charts/nfs-backup/values.yaml
This change limits the number of completed and failed cronjob pods that are retained, to prevent them cluttering up the cluster. Default backup frequency has also been dropped to daily, due to the resource-intensive nature of the s3cmd backup command.
> Nfs backup: configure job garbage collection and changed default schedule to daily

- charts/cpanel/CHANGELOG.md
- charts/cpanel/Chart.yaml
- charts/cpanel/templates/deployment.yaml
- charts/cpanel/templates/secrets.yaml
- charts/cpanel/values.yaml
- Added `TOOLS_DOMAIN` variable
- Added `RSTUDIO_AUTH_CLIENT_DOMAIN` variable
- Added `RSTUDIO_AUTH_CLIENT_ID` variable
- Added `RSTUDIO_AUTH_CLIENT_SECRET` variable
- https://github.com/ministryofjustice/analytics-platform-control-panel/pull/82
- https://github.com/ministryofjustice/analytics-platform-config/pull/21
https://trello.com/c/77FMKVLE/536-3-cp-api-add-endpoint-to-deploy-rstudio
> v0.9.0: Added environment variables needed to deploy RStudio

- charts/cpfrontend/CHANGELOG.md
- charts/cpfrontend/Chart.yaml
- charts/cpfrontend/README.md
- charts/cpfrontend/templates/deployment.yaml
- charts/cpfrontend/templates/secrets.yaml
- charts/cpfrontend/values.yaml
Also added `README.md` and `CHANGELOG.md`.
Part of ticket: https://trello.com/c/BbHaXQXt/562-2-cp-app-add-node-endpoint-to-deploy-a-tool
https://github.com/ministryofjustice/analytics-platform-control-panel-frontend/pull/84
> cpfrontend 1.3.0: Setting `TOOLS_DOMAIN` environment variable

- charts/init-user/templates/role-binding.yml
This assigns the admin user-facing role to a user, scoped to the user's namespace.
> Role-binding to make user's admins in their own namespaces

- charts/cpanel/CHANGELOG.md
- charts/cpanel/Chart.yaml
- charts/cpanel/README.md
- charts/cpanel/templates/deployment.yaml
- charts/cpanel/values.yaml
Set to `True` when k8s RBAC is enabled, the k8s proxy endpoint will then use
the user's JWT token to make requests to kubernetes instead of use the
credentials read from the cluster.
See [PR](https://github.com/ministryofjustice/analytics-platform-control-panel/pull/85)
> cpanel 0.10.0: Added `ENABLE_K8S_RBAC` flag.

- charts/nginx-ingress/Chart.yaml
- charts/nginx-ingress/README.md
- charts/nginx-ingress/templates/NOTES.txt
- charts/nginx-ingress/templates/_helpers.tpl
- charts/nginx-ingress/templates/clusterrole.yaml
- charts/nginx-ingress/templates/clusterrolebinding.yaml
- charts/nginx-ingress/templates/controller-configmap.yaml
- charts/nginx-ingress/templates/controller-customconfig-configmap.yaml
- charts/nginx-ingress/templates/controller-daemonset.yaml
- charts/nginx-ingress/templates/controller-deployment.yaml
- charts/nginx-ingress/templates/controller-hpa.yaml
- charts/nginx-ingress/templates/controller-metrics-service.yaml
- charts/nginx-ingress/templates/controller-service.yaml
- charts/nginx-ingress/templates/controller-stats-service.yaml
- charts/nginx-ingress/templates/default-backend-deployment.yaml
- charts/nginx-ingress/templates/default-backend-service.yaml
- charts/nginx-ingress/templates/headers-configmap.yaml
- charts/nginx-ingress/templates/role.yaml
- charts/nginx-ingress/templates/rolebinding.yaml
- charts/nginx-ingress/templates/serviceaccount.yaml
- charts/nginx-ingress/templates/tcp-configmap.yaml
- charts/nginx-ingress/values.yaml
Turns out we're still not able to use the nginx-ingress chart from the main k8s repo due to issues with Websockets when terminating TLS at the ELB. So I've updated our customised chart using the latest version of the main repo chart.
> Updated nginx-ingress controller from latest upstream

- charts/webapp/Chart.yaml
- charts/webapp/templates/ingress.yaml
The current version of nginx-ingress-controller no longer supports enabling sticky sessions globally, so an ingress annotation is required instead.
> webapp chart: added session affinity ingress annotation

- charts/fluentd/values.yaml
See: https://github.com/kubernetes/kubernetes/issues/53022#issuecomment-332150416
Also
See: https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter
Symlink `/var/log/containers` has been deprecated in favour of `/var/log/pods`
for our version of the docker daemon for kubernetes metadata.
No noticeable symptoms other than log errors.
> Kubernetes MetaData Plugin

- charts/rstudio/templates/deployment.yml
- charts/rstudio/templates/service-account.yaml
Adding service account for auditing purposes.  The RStudio instances do not need
to access api resources therefore need no permissions.
However all rstudio pods run as __default__ service-account for that
namespace which is fine but makes querying a little confusing when
trying to match accounts with bindings.
> Rstudio Service Account

- charts/rstudio/CHANGELOG.md
- charts/rstudio/Chart.yaml
- charts/rstudio/templates/deployment.yml
- charts/rstudio/templates/secrets.yml
- charts/rstudio/values.yaml
Set environment variables used by [rstudio-auth-proxy](https://github.com/ministryofjustice/analytics-platform-rstudio-auth-proxy/pull/12/files):
- `APP_PROTOCOL` will always be `https`
- `APP_HOST` is something like `joe-rstudio.tools.example.com`
This needs to be merged before the [rstudio-auth-proxy changes](https://github.com/ministryofjustice/analytics-platform-rstudio-auth-proxy/pull/12/files) (if not logout would be broken, rest should still be fine so not a massive deal really)
https://trello.com/c/t90fEmBs/647-4-update-rstudio-auth-proxy-to-use-hosted-auth0-login
> RStudio 1.3.0: Pass env variable necessary for hosted login page logout

- charts/cpfrontend/CHANGELOG.md
- charts/cpfrontend/Chart.yaml
- charts/cpfrontend/templates/deployment.yaml
See related PR: https://github.com/ministryofjustice/analytics-platform-control-panel-frontend/pull/131
> cpfrontent 1.3.4: Removed `APP_PORT` environment variable

- charts/rstudio/templates/service-account.yaml
The value is `username` not `Username`
> Fix rstudio service account typo

- charts/init-user/templates/create-user-home-job.yml
The persistent volume claim `nfs-homes` lives in the default namspace.  Running the
Job works fine if the namespace in your context is set to default but in
the event that it is not.  The job will fail.
> Create User Home Namespace

- charts/rstudio/CHANGELOG.md
- charts/rstudio/Chart.yaml
- charts/rstudio/values.yaml
See quay.io/mojanalytics/rstudio-auth-proxy tag v1.3.0
> RStudio v1.3.0 proxy to use Auth0 hosted login page

- charts/cpanel/templates/cluster-role.yaml
- charts/cpanel/templates/deployment.yaml
- charts/cpanel/templates/role-binding.yaml
- charts/cpanel/templates/service-account.yaml
In the backgroud the control panel invokes `helm` commands to manage a
user's applications like rstudio. `helm` itself requires that the
account invoking it be able to discover `tiller`. To discover `tiller` the account
at the very least will need to be able to __list__ `pods` in `kube-system` (perhaps
because helm assumes that is where tiller is?) and forward ports.
> RBAC: CPANEL

- charts/init-user/Chart.yaml
The version didn't change which means the repository index rebuild
didn't get triggered.
> init-user: Bumped version

- charts/rstudio/CHANGELOG.md
- charts/rstudio/Chart.yaml
- charts/rstudio/templates/deployment.yml
- charts/rstudio/values.yaml
By using [new version of rstudio-auth-proxy](https://github.com/ministryofjustice/analytics-platform-rstudio-auth-proxy/pull/13) (`v1.4.1`)
Also using [rstudio-auth-proxy's `GET /healthz` endpoint](https://github.com/ministryofjustice/analytics-platform-rstudio-auth-proxy/pull/14) instead of `GET /login` as readiness probe.
> RStudio 1.4.0: Enabled Silent SSO

- charts/jupyter-lab/Chart.yaml
- charts/jupyter-lab/README.md
- charts/jupyter-lab/templates/_helpers.tpl
- charts/jupyter-lab/templates/deployment.yaml
- charts/jupyter-lab/templates/ingress.yaml
- charts/jupyter-lab/templates/secrets.yaml
- charts/jupyter-lab/templates/service-account.yaml
- charts/jupyter-lab/templates/service.yaml
- charts/jupyter-lab/values.yaml
Jupyter Lab Helm Chart
Deploys Jupyter lab data-science notebook [stack](https://github.com/jupyter/docker-stacks/tree/master/datascience-notebook) 
Shares the same storage(PVC) as rstudio-server.
Uses image: https://github.com/ministryofjustice/analytics-platform-jupyter-notebook
> Jupyter-Lab: Initial Commit

- charts/rstudio/CHANGELOG.md
- charts/rstudio/Chart.yaml
- charts/rstudio/README.md
- charts/rstudio/templates/deployment.yml
- charts/rstudio/values.yaml
Using new version of `rstudio-auth-proxy` (`v1.4.2`) which now
sets session cookies' `Max-Age` to expire session after 1h.
This can be optionally be configured via `authProxy.cookieMaxAge` chart value.
See also: https://github.com/ministryofjustice/analytics-platform-rstudio-auth-proxy/pull/15
> rstudio 1.4.1: Session cookies expire after 1 hour (by default)

- charts/jupyter-lab/files/pip-user-home.sh
- charts/jupyter-lab/templates/configmap-bash-profile.yaml
- charts/jupyter-lab/templates/job-bash-profile.yaml
Trello: https://trello.com/c/HCdzYjGQ
Adds a shell `alias` to include `--user` flag when running `pip` with
`install` command.
This results in packages being installed to the invoking user's home
directory.  Usually under `$HOME/.local/`.
All other `pip` commands are left as is.
> pip: Package Home

- charts/jupyter-lab/templates/ingress.yaml
The control panel constructs a URL for an app not based on the the
ingress host. Possibly by chart name.
Modifying ingress host to match behaviour of control panel.
> Jupyter Ingress Host

- charts/cpfrontend/CHANGELOG.md
- charts/cpfrontend/Chart.yaml
- charts/cpfrontend/templates/deployment.yaml
This should fix the `503` errors caused by the use of `/login` as
a readiness probe after enabling silent SSO.
Ticket: https://trello.com/c/fPZGrSYt/695-1-add-healtcheck-to-cp-ui
> cpfrontend 1.3.5: Using /healthz endpoint

- charts/README.md
Adding path for clarity.
Upstream [PR](https://github.com/coreos/prometheus-operator/pull/917) means we do not have to set rbac anymore as it is now true by default.
> Prometheus Doc

- charts/kibana-auth-proxy/CHANGELOG.md
- charts/kibana-auth-proxy/Chart.yaml
- charts/kibana-auth-proxy/README.md
- charts/kibana-auth-proxy/templates/deployment.yaml
- charts/kibana-auth-proxy/values.yaml
- Fixed proxy version/tag instead of using `latest`
- Use newly added `/healthz` endpoint for healthcheck
- Proxy was updated to:
- use Auth0 hosted login page instead of local login page
- enabled silent SSO enabled
- session cookies expire after 1 hour
- Other changes, see: https://github.com/ministryofjustice/analytics-platform-kibana-auth-proxy/pull/1
https://trello.com/c/robNgbzG/651-3-update-kibana-auth-proxy-to-use-hosted-auth0-login
> kibana-auth-proxy 1.1.0: Proxy to use Auth0 hosted login page

- charts/init-user/templates/role-binding.yml
The Kubernetes API prefixes the 'IssuerURL' to all UsernameClaims other than email.
To use the nickname claim, we must prefix the subject's name with the 'IssuerURL' until which point kops supports the --oidc-username-prefix flag.
See: https://kubernetes.io/docs/admin/authentication/#configuring-the-api-server
Also, see Aldo's PR where he added support for --oidc-username-prefix
to kops: kubernetes/kops#4085
> OIDC Username Claim

- charts/kibana-auth-proxy/CHANGELOG.md
- charts/kibana-auth-proxy/Chart.yaml
- charts/kibana-auth-proxy/templates/ingress.yaml
Ingress resource doesn't need the following annotation anymore
nginx.ingress.kubernetes.io/force-ssl-redirect: true
Bumped chart to version `1.1.2`
> kibana-auth-proxy: Fixed redirect loop caused by ingress annotation

- charts/webapp/CHANGELOG.md
- charts/webapp/Chart.yaml
- charts/webapp/templates/deployment.yaml
- charts/webapp/values.yaml
Some deployed apps (shiny apps specifically) broke because somehow
they were using `latest` as proxy tag. Not sure why (probably they
were installed before we pinned the version)
Their healthcheck was also broken because they were hitting `/login`
as a surrogate healthcheck test. We're now using the `/healthz`
endpoint introduced by `auth-proxy-v0.1.2`.
> webapp 1.3.7: Fixed proxy healthcheck

- charts/webapp/values.yaml
After upgrading K8s to 1.8.9 we fell victim to https://github.com/kubernetes/kubernetes/pull/58720
Ideally the fluentd container should source values from env vars instead
of writing themto a config file. See: [entryPoint](https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/docker-image/v0.12/debian-elasticsearch/entrypoint.sh)
The `set -e` does not help either.
**Deployed** in alpha
> FluentD Fork

- charts/fluentd/values.yaml
Trello: https://trello.com/c/W5NVPEQ0
After upgrading K8s to 1.8.9 we fell victim to
https://github.com/kubernetes/kubernetes/pull/58720
Ideally the fluentd container should source values from env vars instead
of writing them to a config file. See:
[entryPoint](https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/docker-image/v0.12/debian-elasticsearch/entrypoint.sh)
The `set -e` does not help either.
The resource change adresses the logs mentioned in the [trello](https://trello.com/c/W5NVPEQ0) ticket.
Upstream Ref: https://github.com/kubernetes/kubernetes/pull/48970
Ruby (Particularly in Alpha) is throwing OOM events as it exceeds it's
limits of 256MB and sometimes spikes well above.  When this occurs the
Kubelet daemon kills the pod and recreates it (As it is supposed to). …
> FluentD Temp Fork

- charts/rstudio/CHANGELOG.md
- charts/rstudio/Chart.yaml
- charts/rstudio/values.yaml
Users get a `unable to establish a connection with the R session` when
trying to interact with RStudio console once session expired.
The RStudio auth-proxy session cookies expired after 1h but as users keep
they RStudio tab open for longer and because of how RStudio works (it's
essentially a single page app not making new HTTP requests).
Session now lasts 8 hours.
https://trello.com/c/CP1tWlzK/726-2-rstudio-unable-to-establish-a-connection-with-the-r-session-every-hour
> rstudio 1.4.2: Sessions last 8 hours

- charts/jupyter-lab/CHANGELOG.md
- charts/jupyter-lab/Chart.yaml
- charts/jupyter-lab/templates/secrets.yaml
Fixing auth proxy callback envvar to point to the correct endpoint.
Currently callback url has just `jupyter` instead of `jupyter-lab`
causing users to be redirected to default backend.
>  Jupyter Auth0 CallBack URL

- charts/rstudio/.helmignore
- charts/rstudio/migrations/20180411-1155_increase_cookie_maxage.sh
The migration script will set `COOKIE_MAXAGE=28800` on each of the
`rstudio-auth-proxy` containers for deployments matching the label
`app=rstudio` in each of the namespaces starting with `user-*`.
You caThe script has also a `DRYRUN` "o"
- Be sure you're pointing to the right k8s cluster (I strongly advice to
point to `dev` cluster before playing with it)
- Be sure the script is executable
```bash
./charts/rstudio/migrations/20180411-1155_increase_cookie_maxage.sh
```
The script also has a `DRYRUN` option which is useful to see what the effect
of the changes will be without actually making changes:
```bash
DRYRUN=true ./charts/rstudio/migrations/20180411-1155_increase_cookie_maxage.sh
```
This will retro-apply change added in [`rstudio-1.4.2`](https://github.com/ministryofjustice/analytic …
> Add RStudio migration which increses session expiration to 8h

- charts/fluentd/templates/clusterrole.yaml
- charts/fluentd/templates/clusterrolebinding.yaml
- charts/fluentd/templates/configmap.yaml
- charts/fluentd/templates/daemonset.yaml
- charts/fluentd/templates/secrets.yaml
- charts/fluentd/templates/serviceaccount.yaml
- charts/fluentd/values.yaml
Elasticsearch has been degraded up until recently due to high memory pressure caused by slow garbage collection. 
Leading up to this FluentD has been constantly logging exceptions mainly related to 
* connection issues with elasticsearch 
and 
* continuously exceeding buffer limits. partially due to misconfiguration  
Trial and error while parsing docs has lead me to what looks like a semi-stable configuration.
1. Get a pod id to parse logs from
`kubectl get po --namespace kube-system | grep logging`
2. Parse the logs to hopefully see a reduced frequency of exceptions
`kubectl logs < POD ID > --namespace kube-system`
> Fluentd tuning

- charts/concourse-org-pipeline/Chart.yaml
- charts/concourse-org-pipeline/files/pipeline.yaml
- charts/concourse-org-pipeline/files/set-pipeline.sh
- charts/concourse-org-pipeline/templates/configmap.yaml
- charts/concourse-org-pipeline/templates/job.yaml
- charts/concourse-org-pipeline/templates/secrets.yaml
- charts/concourse-org-pipeline/values.yaml
* Runs a Kubernetes Job, in which a script sets a Concourse pipeline for a specified Github org, which scans the org repos for build files (currently `Jenkinsfile`, but soon to change) and creates a deploy pipeline for those repos.
> Add chart for setting up Concourse pipeline for a Github org

- charts/idler/CHANGELOG.md
- charts/idler/Chart.yaml
- charts/idler/README.md
- charts/idler/values.yaml
Fixes a bug causing the idler to idle RStudio instances even if their
CPU usage is above the threashold.
Related PR
========
https://github.com/ministryofjustice/analytics-platform-idler/pull/8
Ticket
====
https://trello.com/c/jgHhwqcF/736-fix-bug-with-hibernations-idling-so-that-users-can-run-jobs-overnight
> idler 0.2.1: Fix idling of used RStudio instances

- update-packages
Old logic/problem
=================
The existing logic to determine if a package for an helm chart
needed update was comparing the time of the last commit for the
helm chart with the time of the last commit of the index file.
This was mostly working but not always. It wasn't updating an helm
chart package when another PR was merged before.
In this case the index was rebuilt and therefore commits older than
this time were not causing the re-build of the index/packages.
New logic
=========
I've tweaked the `update-packages` script to compare the time when
the chart code was last updated with the time one of the chart's tarballs
was last updated.
This means that each chart package is treated independently and the risk
of non-update is limited.
Caveat (spelled right this time) …
> Improve logic of script which updates helm chart repository

- charts/idler/CHANGELOG.md
- charts/idler/Chart.yaml
- charts/idler/templates/clusterrole.yaml
- charts/idler/values.yaml
- Better handling of unhealthy pods (missing metrics data)
- Fixes logging
- Added required to list pods and pods' metrics
(plus the fix to the missing `metrics_api` file in Docker image)
> idler-0.2.3 - various fixes to docker image/permissions/logging

- charts/idler/CHANGELOG.md
- charts/idler/Chart.yaml
- charts/idler/README.md
- charts/idler/templates/cronjob.yaml
- charts/idler/values.yaml
This was [supported by the idler](https://github.com/ministryofjustice/analytics-platform-idler/pull/10/files#diff-225132354aa2a9f4d7ecebb48833c06bR26) but wasn't added to the helm chart.
Using [new version of idler](https://github.com/ministryofjustice/analytics-platform-idler/pull/11) with more debug logging.
> idler-0.2.4 - Added value to easily change log level

- charts/rstudio/CHANGELOG.md
- charts/rstudio/Chart.yaml
- charts/rstudio/values.yaml
New RStudio image accidentally deployed to all users after previous
merge which included new Rstudio image.  It builds
the latest tag off master.
Reverting and pinning version.
> Rstudio Image Tag

- charts/concourse-org-pipeline/files/pipeline.yaml
* Change automatic check frequency from default of once per minute, to once per day
* Checks are performed via the Github webhook on creation of a release, so polling every minute is unnecessary and runs the risk of using up our Github API rate limit.
* Can't actually turn off polling - setting to `0` results in continuous polling 👎
> Only check Github org once per day

- charts/rstudio/migrations/set_rstudio_image_tag.sh
[trello](https://trello.com/c/R5DeH04g)
Script to modify rstudio image tags.  Useful for rolling out versions or
just serving as an example.
Gated with `dry-run` flag for no-op runs to what will be changed if run.
1. Execute the script and answer `y` to invoke a dry run.  You will see output for deployments that will be affected.  i.e. __Does not match __ the image defined in the script. 
In dev, that will be my deployment
> Set Rstudio Image Tag

- charts/rstudio/CHANGELOG.md
- charts/rstudio/Chart.yaml
- charts/rstudio/migrations/set_rstudio_image_tag.sh
- charts/rstudio/values.yaml
Use `rstudio-auth-proxy` `v1.4.3`, this version of the proxy updates some
dependencies and fixes CVE-2018-3728.
See
- Proxy tag: https://github.com/ministryofjustice/analytics-platform-rstudio-auth-proxy/releases/tag/v1.4.3
- CVE-2018-3728: https://nvd.nist.gov/vuln/detail/CVE-2018-3728
> rstudio-1.5.2: Fix auth-proxy/hoek vulnerability

- charts/concourse-org-pipeline/CHANGELOG.md
- charts/concourse-org-pipeline/Chart.yaml
- charts/concourse-org-pipeline/templates/secrets.yaml
- charts/concourse-org-pipeline/values.yaml
* Added `secrets.cpanel-api-url` secret, intended to be overridden in config repo. This contains the base URL of the Control Panel API which is used to fetch the app IAM role during webapp deployment.
* Bumped the version of the [Concourse Github Org resource to 0.3.9](https://github.com/ministryofjustice/analytics-platform-concourse-github-org-resource/pull/6)
* Introduces the task to fetch the IAM role and pass it to helm
* Reduces org polling interval to once every 24 hours - checks are intended to be
triggered via Github webhook instead.
> Add cpanel-api-url secret for org pipeline

- charts/jupyter-lab/CHANGELOG.md
- charts/jupyter-lab/Chart.yaml
- charts/jupyter-lab/files/pip-user-home.sh
- charts/jupyter-lab/values.yaml
Jupyter was failing to autoload `.profile`
Adding `.bash_aliases` file instead which `.bashrc` checks exists.
Sanity checked and simplified evaluation as we're just matching an exact
string.
bumping Jupyter image with modified `PATH`.
See: ministryofjustice/analytics-platform-jupyter-notebook#5
> Default Package Home

- charts/webapp/CHANGELOG.md
- charts/webapp/Chart.yaml
- charts/webapp/templates/deployment.yaml
- charts/webapp/values.yaml
Fluentd keeps crashing due to upstream daemonset image not working with
config changes introduced with K8s 1.8.  i.e. mounts now default to
read-only.
FluentD will also crash due to OOM errors from ruby evident by viewing
kubelet journal.  Default limit is 256MB whereas fluentD uses on
avaerage 265MB.
> FluentD Crash

- charts/cpanel/CHANGELOG.md
- charts/cpanel/Chart.yaml
- charts/cpanel/templates/deployment.yaml
* Add missing environment variable to deployment. Value and secret were already there, just missing the deployment.
> Fix ElasticSearch env var in CPanel API

- charts/cpanelapi-pipeline/files/pipeline.yaml
* Helm repo moved to S3, so this change updates the URL used in the pipeline
> Update helm repo URL for cpanel pipeline

- charts/kubernetes-dashboard/templates/cluster-role.yaml
Removing read-only on all `configmaps` from kube-dashboard read-only
role.  Might be over-kill but will protect us if anyone accidentally
deploys a secret in one.
> Dashboard Role: configmap

- charts/webapp/templates/fluentd-configmap.yml
Tuning fluentd to improve stability.
- Increased buffer params
- Removed flush interval as this conflicts with `slow_flush_log`
- Incresed request timeout
> WebApp: FluentD tuning

- charts/concourse-admin-team/CHANGELOG.md
- charts/concourse-admin-team/Chart.yaml
- charts/concourse-admin-team/README.md
- charts/concourse-admin-team/templates/secrets.yaml
- charts/concourse-admin-team/values.yaml
* Add a Helm chart to create secrets used by Concourse pipelines owned by the `concourse-admin` team (see https://github.com/ministryofjustice/analytics-platform-concourse-pipelines)
* See [values](https://github.com/ministryofjustice/analytics-platform-config/pull/60)
> Add chart for concourse-admin team

- charts/concourse-admin-team/CHANGELOG.md
- charts/concourse-admin-team/Chart.yaml
- charts/concourse-admin-team/templates/secrets.yaml
* Fix secrets template. Secrets names must be lowercase alphanumeric, `-` or `.`
> Fix concourse-admin-team secrets

- charts/webapp/migrations/upgrade_releases.sh
Interactive shell script to perform chart upgrades for shiny-apps in k8s namespace: `apps-prod`
We use `helm get values` to ensure we have all values required to perform
an upgrade. This does pose questions about conflicts during a user
provided values merge and ideally we want whatever is in the repo to take precedence
but for now, this solution provides the most predictable behaviour.    
Please see issue [here](https://github.com/kubernetes/helm/issues/3957) for more information
__With__ or __Without__ flags
- Select `y` when prompted to perform __dry_run__
With defaults:
1. Run script (./upgrade_release.sh) with no flags
With Options:
1. Run script (./upgrade_release.sh) with `-h` to view usage
```
usage: All arguments are optional
-e - Environment e.g. dev or alpha, Default: alpha
-d …
```
> Helm: Upgrade Webapp script

- charts/rstudio/CHANGELOG.md
- charts/rstudio/Chart.yaml
- charts/rstudio/values.yaml
[Trello](https://trello.com/c/0R72UYbH)
Adjusting upper limit of memory for rstudio instances.  Increased
requests to hopefully reduce binpacking by the scheduler.  I'm hoping
this would reduce occurences of the scheduler having to reschedule pods,
should a user max-out their memory.
> Adjust RStudio Resources

- charts/webapp/CHANGELOG.md
- charts/webapp/Chart.yaml
- charts/webapp/values.yaml
This new version of auth proxy uses `lock` instead of `lock-passwordless` which
is now deprecated by auth0
> Webapp: Upgrade to v0.1.3 docker image of auth-proxy

- charts/webapp/CHANGELOG.md
- charts/webapp/Chart.yaml
- charts/webapp/templates/fluentd-configmap.yml
Mismatched `FLUENT_ELASTICSEARCH_USERNAME` env var in configmap
Set reload on failure to __false__.  See: https://github.com/uken/fluent-plugin-elasticsearch/issues/257#issuecomment-348946393
> Reload on Failure

- charts/concourse-org-pipeline/CHANGELOG.md
- charts/concourse-org-pipeline/Chart.yaml
- charts/concourse-org-pipeline/README.md
- charts/concourse-org-pipeline/templates/secrets.yaml
This commit adds placeholder for AWS key and secret that are then available to
concourse pipelines which intend to list AWS IAM roles
> Concourse: add aws secrets to list IAM roles

- charts/jupyter-lab/templates/deployment.yaml
- charts/jupyter-lab/values.yaml
Fixing Readiness probe's path
See [here](https://github.com/ministryofjustice/analytics-platform-auth-proxy/blob/2cfd41ed0d215a495ab596540276b2267ba88c4e/app/base/routes.js#L8)
Setting the session cookie maxage to 10 hours
This will result in the auth-proxy not having to go through the login process when/if the connection drops over a 10 hour period.
> Jupyter: auth-proxy

- charts/jupyter-lab/CHANGELOG.md
- charts/jupyter-lab/Chart.yaml
- charts/jupyter-lab/values.yaml
[Trello](https://trello.com/c/M1snktNZ)
Update datascience-notebook image tag from 0.3.3 to 0.4.0. Relates to [PR](https://github.com/ministryofjustice/analytics-platform-jupyter-notebook/pull/8)
> Update Jupyter Image Tag

- charts/airflow-k8s/Chart.yaml
- charts/airflow-k8s/templates/hooks/init-airflow-ns-hook.yml
- charts/airflow-k8s/templates/ingress.yml
- charts/airflow-k8s/values.yaml
- charts/init-user/Chart.yaml
- charts/init-user/templates/namespace.yml
- charts/kube2iam/Chart.yaml
- charts/kube2iam/templates/daemonset.yml
This enables `regexp` namespace restrictions for kube2iam and has some fallout.
By default un-annotated namespaces can no longer assume _any role at all_.
* new file:   airflow-k8s/templates/hooks/init-airflow-ns-hook.yml
This is a helm hook, kind of like a database migration that on installing
this updated version of the chart will annotate the existing `airflow`
namespace with the required annotation
* modified:   init-user/templates/namespace.yml
New user namespaces need will have new annotation to allow them to assume
roles starting with dev or alpha
> Kube2iam: Update to use MoJ Kube2iam regexp ns restrictions

- charts/jupyter-lab/CHANGELOG.md
- charts/jupyter-lab/Chart.yaml
- charts/jupyter-lab/templates/ingress.yaml
- charts/jupyter-lab/values.yaml
- charts/rstudio/CHANGELOG.md
- charts/rstudio/Chart.yaml
- charts/rstudio/templates/ingress.yml
[Trello](https://trello.com/c/M1snktNZ)
- Added tls config to ingress objects for Rstudio and Jupyter.  This is required for tls termination with the nginx ingress controller.
- Auth-proxy image tag from 0.1.4 to 0.1.3 while investigating ssl redirect issues
> Jupyter & Rstudio Ingress

- charts/README.md
- charts/nginx-ingress/Chart.yaml
- charts/nginx-ingress/README.md
- charts/nginx-ingress/templates/_helpers.tpl
- charts/nginx-ingress/templates/clusterrole.yaml
- charts/nginx-ingress/templates/clusterrolebinding.yaml
- charts/nginx-ingress/templates/controller-daemonset.yaml
- charts/nginx-ingress/templates/controller-deployment.yaml
- charts/nginx-ingress/templates/controller-hpa.yaml
- charts/nginx-ingress/templates/controller-metrics-service.yaml
- charts/nginx-ingress/templates/controller-nlb-service.yaml
- charts/nginx-ingress/templates/controller-poddisruptionbudget.yaml
- charts/nginx-ingress/templates/controller-service.yaml
- charts/nginx-ingress/templates/controller-stats-service.yaml
- charts/nginx-ingress/templates/default-backend-deployment.yaml
- charts/nginx-ingress/templates/default-backend-poddisruptionbudget.yaml
- charts/nginx-ingress/templates/default-backend-service.yaml
- charts/nginx-ingress/templates/role.yaml
- charts/nginx-ingress/templates/rolebinding.yaml
- charts/nginx-ingress/templates/serviceaccount.yaml
- charts/nginx-ingress/values.yaml
[Trello](https://trello.com/c/M1snktNZ)
[Config PR](https://github.com/ministryofjustice/analytics-platform-config/pull/72)
As part of the above ticket, I thought it would be a good time to upgrade
the ingress stack.
Apart from minor version increments, the main difference is the way
custom __nginx__ configuration is handled/applied.
The recent version of [Ingress-Nginx](https://github.com/kubernetes/ingress-nginx) now supports [configmaps](https://github.com/kubernetes/ingress-nginx/blob/0f7ef88a80b9011024194f287b720755a7986099/docs/user-guide/nginx-configuration/configmap.md) which allows applying custom configuration without having to override/fork the entire __nginx__ configuration file.
Such as adding snippets to location or …
> Ingress-Nginx: Upgrade

- charts/airflow-k8s/CHANGELOG.md
- charts/airflow-k8s/Chart.yaml
- charts/airflow-k8s/templates/configmap.yml
This was causing emails to not be sent.
> airflow-k8s 0.0.5: Fixed missing SMTP credentials in k8s operator pod

- charts/idler/CHANGELOG.md
- charts/idler/Chart.yaml
- charts/idler/values.yaml
This bumps the image version of the idler to a version that supports nanocores
as a unit/format for cpu usage.
> Idler 1.0.0 (appVersion: v0.3.0): Support Nanocores

- charts/jupyter-lab/CHANGELOG.md
- charts/jupyter-lab/Chart.yaml
- charts/jupyter-lab/templates/deployment.yaml
- charts/rstudio/CHANGELOG.md
- charts/rstudio/Chart.yaml
- charts/rstudio/templates/deployment.yml
Add `idleable: "true"` so that Jupyter and Rstudio can opt-in to being idled with a single label selector
> JupyterLab & RStudio: Add idleable label

- charts/concourse-org-pipeline/Chart.yaml
- charts/concourse-org-pipeline/files/pipeline.yaml
- charts/concourse-org-pipeline/files/set-pipeline.sh
- charts/concourse-org-pipeline/templates/job.yaml
- charts/concourse-org-pipeline/templates/secrets.yaml
- charts/concourse-org-pipeline/values.yaml
The old chart used to target a pipeline called `moj-analytical-services` because
the pipeline name was based on the org name. At some point we manually deployed
this to a pipeline called `create-webapp-pipelines` in the admin team.
These changes update the chart to reflect the current state of the world.
I've also updated the pipeline to read the github tokens from k8s secrets
instead of having them passed in with fly
> Concourse: Target correct pipeline

- charts/idler/CHANGELOG.md
- charts/idler/Chart.yaml
- charts/idler/values.yaml
Using a new version of idler (`v0.3.1`) with more support for cpu metrics in
microcorescores:
https://github.com/ministryofjustice/analytics-platform-idler/pull/20
> Idler v0.3.1: Version bump

- charts/idler/CHANGELOG.md
- charts/idler/Chart.yaml
- charts/idler/values.yaml
Generic support for idling any tool by using app label instead of assuming the
tool `ingress` name is the same as the tool `deployment` name.
> Idler v0.4.0: Support for idling Jupyter-lab

- charts/unidler/CHANGELOG.md
- charts/unidler/Chart.yaml
- charts/unidler/templates/clusterrole.yaml
- charts/unidler/templates/deployment.yaml
- charts/unidler/values.yaml
- Changed Docker image to use [`go-unidler`](https://github.com/ministryofjustice/analytics-platform-go-unidler) instead of ["old" `unidler` (Python)](https://github.com/ministryofjustice/analytics-platform-unidler)
- Use `/healthz` endpoint provided by `go-unidler` to check readiness/liveness.
- Increased `replicaCount` from `1` to `3` as `go-unidler` is stateless and unidling is idempotent
- `ingress.className` defaults to `"nginx"` again (not `"istio"`)
- removed unused values (`logLevel`)
> unidler v3.0.0: Use `go-unidler`

- charts/jupyter-lab/CHANGELOG.md
- charts/jupyter-lab/Chart.yaml
- charts/jupyter-lab/values.yaml
This updates the Jupyter image tag to v0.6.0, which adds geospatial functionality, support for s3 access in spark, and the latest version of jupyter lab.
Might want to pay a little more attention to this PR than usual since it's my first into the helm charts repo!
> Update jupyter images to latest tag

- charts/rstudio/CHANGELOG.md
- charts/rstudio/Chart.yaml
- charts/rstudio/templates/deployment.yml
- charts/rstudio/templates/service.yml
Looks like sometimes auth proxy crashes but container is not terminated (see ticket)
Looking at the RStudio deployment I see that we defined a `readinessProbe` but not a `livenessProbe`, this is likely to be the cause of the problem.
Just a reminder:
- `readinessProbe` determine whether the container should receive traffic
- `livenessProbe` determine if the container is healthy and whether kubernetes will terminate it or not
- `initialDelaySeconds` on `livenessProbe` needs to be enough for the pod to start otherwise k8s will terminate the pod before it can be healthy and you’ll end-up in a loop
- Don't hardcode target port in `Service`, use provided value
- Renamed ports in `Deployment` to be more explicit and avoid any possible
confusion (they're called `proxyPort` and `rstudioPort` …
> RStudio 1.5.7: Better probes

- charts/jupyter-lab/CHANGELOG.md
- charts/jupyter-lab/Chart.yaml
- charts/jupyter-lab/templates/deployment.yaml
- Added `livenessProbe` to be sure pods are terminated when unhealthy
- Reduced probes' `periodSeconds` from `5` to `2`
- Renamed ports in `Deployment` to `proxy`/`jupyter` instead of using `http`
for everything which could lead to confusion
- Fixed indentation in `Deployment` YAML file
Ticket: https://trello.com/c/92huREQl/1340-fix-liveness-probe-auth-proxy-crash-not-being-handled
Similar PR: https://github.com/ministryofjustice/analytics-platform-helm-charts/pull/237
> jupyter-lab 0.1.10: Better probes

- charts/webapp/CHANGELOG.md
- charts/webapp/templates/deployment.yaml
- Added `livenessProbe` to proxy container
- Added `readinessProbe` to webapp container
- Reduced proxy probe' `periodSeconds` to `2`
- Named all ports in `Deployment` (`proxy`/`webapp`) instead of using `http`
for everything which could lead to confusion
Ticket: https://trello.com/c/92huREQl/1340-fix-liveness-probe-auth-proxy-crash-not-being-handled
See similar PR: https://github.com/ministryofjustice/analytics-platform-helm-charts/pull/237
> webapp 1.3.16: Better probes

- charts/webhook-dispatcher/.helmignore
- charts/webhook-dispatcher/Chart.yaml
- charts/webhook-dispatcher/templates/_helpers.tpl
- charts/webhook-dispatcher/templates/deployment.yaml
- charts/webhook-dispatcher/templates/ingress.yaml
- charts/webhook-dispatcher/templates/secrets.yaml
- charts/webhook-dispatcher/templates/service.yaml
- charts/webhook-dispatcher/values.yaml
This is a new chart for deploying a github org hook to concourse pipeline
service. This will allow us to reduce polling frequency for concourse pipelines
because they will now be triggered by a single org webhook
> Webhook Dispatcher

- charts/init-platform/templates/create-nfs-dir-job.yml
This job mounts the NFS disk at `/` and creates the `/users/homes` dir. If you don't do this then the `efs-homes` PersistentVolume cannot be mounted because it mounts at that dir.
@kerin and I figured this must have been done manually for alpha & dev's softnas disks. This Job automates it.
Tested on accelerator environment.
> Create initial /users/homes dir on the NFS disk

- charts/jupyter-lab/CHANGELOG.md
- charts/jupyter-lab/Chart.yaml
- charts/jupyter-lab/templates/deployment.yaml
Related to [PR](https://github.com/ministryofjustice/analytics-platform-helm-charts/pull/240)
Intermittently some users are unable to launch Jupyter-Lab successfully
due to probe failures.  There doesn't appear to be a pattern to failing replicas. All we see in the pod
description are the `Liveness/Readiness probes are failing with
getsockopt: connection refused` errors.
The errors are resolved by increasing the values of the probes for
Jupyter or removing the probes entirely.  See [Probe Configuration](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes)
> jupyter-lab 0.1.11: Better probes adjustment

- charts/cluster-autoscaler/CHANGELOG.md
- charts/cluster-autoscaler/Chart.yaml
- charts/cluster-autoscaler/templates/deployment.yaml
- charts/cluster-autoscaler/templates/rolebinding.yaml
Not sure why yet but for some reason (in alpha), __cluster-autoscaler__ deployed it's status `configmap` to `namespace: default`.
- Added `Rolebinding` that allows __cluster-autoscaler__ to read the `configmap: cluster-autoscaler-status` in `namespace: default`
__Cluster-AutoScaler__ assumes (in alpha only) that it's deployed to `namespace: kube-system`
- Added `--namespace=default` flag as __cluster-autoscaler__ assumes that it's deployed to `namespace: kube-system`
Added __CHANGELOG__
> Cluster AutoScaler (alpha)

- charts/cran-proxy/.helmignore
- charts/cran-proxy/Chart.yaml
- charts/cran-proxy/templates/_helpers.tpl
- charts/cran-proxy/templates/deployment.yaml
- charts/cran-proxy/templates/ingress.yaml
- charts/cran-proxy/templates/service.yaml
- charts/cran-proxy/values.yaml
This is a chart for hosting a CRAN proxy in our cluster. The cran proxy can
speed up installation of binary R packages for both users and webapps.
> CRAN Proxy Chart

- charts/jupyter-lab/CHANGELOG.md
- charts/jupyter-lab/Chart.yaml
- charts/jupyter-lab/templates/deployment.yaml
Modifying `livenessProbe` and `readinessProbe` to type `exec` for Jupyter container
Since introducing probes for Jupyter we have intermittently witnessed
instability when starting the `pod`.
At present we're still unsure as the root cause of the probes failing
for a seemingly healthy container.  The response from Jupyter to the probes on
some occassions appears to be invalid. Initially the probes were introduced
to address failures with the authentication proxy container and they
appear to be working.
> Better Probes 3

- charts/cluster-autoscaler/templates/poddisruptionbudget.yaml
Another alpha observation where it could just be pure chance. CA
(cluster-autoscaler) lands on a node that meets the criteria for scale
down. Cluster Autoscaler has issues across AZs so when CA is evicted, it errors
upon startup trying to acquire leader lease (I think) and requires
manual intervention.
Adding `PodDisruptionBudget` so CA leaves itself (node) alone.
**note**
This has been in flight for a few days and appears to have settled in.
> PodDisruption Cluster AutoScaler

- charts/cran-proxy/Chart.yaml
- charts/cran-proxy/values.yaml
This version only updates documentation but I thought it would be good for the
chart to match the latest version.
> CRAN-Proxy: bump version to v0.2.3

- charts/jupyter-lab/CHANGELOG.md
- charts/jupyter-lab/Chart.yaml
- charts/jupyter-lab/templates/deployment.yaml
Since last chart update stability has continued to decrese due what
appears to be a command in the Dockerfile taking a long time.  The base
image was updated 2 months ago and may have been fixed since.
This PR is on standby in case we have not confirmed a fix by COB.
> Remove Jupyter Probes

- charts/jupyter-lab/CHANGELOG.md
- charts/jupyter-lab/Chart.yaml
- charts/jupyter-lab/templates/deployment.yaml
- charts/jupyter-lab/values.yaml
The probes are back now the underlying problem causing slow jupyter startup has
been identified and fixed. The fix was to run the jupyter container as uid=1001
so it matches rstudio. We were doing this in the docker file before using the
NB_UID environment variable but the presence of that caused the underlying
jupyter base image to `chown` the users' home directory. The bigger the home
directory, the slower this made startup.
> JupyterLab v0.1.14: Return of the probes

- charts/jupyter-lab/Chart.yaml
- charts/jupyter-lab/values.yaml
This solves a redirect login loop bug and also bumps some dependencies' versions
> JupyterLab: Upgrade auth_proxy image version

- charts/rstudio/CHANGELOG.md
- charts/rstudio/Chart.yaml
- charts/rstudio/values.yaml
- Bump version of rstudio image (3.4.2-6), it now points at the cran proxy, has boto3
installed by default and is able to build udunits2 r package
- Change pull policy for rstudio container to be 'IfNotPresent' instead of 'Always'
> Rstudio: bump image version

- charts/cran-proxy/Chart.yaml
- charts/cran-proxy/templates/deployment.yaml
- charts/cran-proxy/values.yaml
New base image now supports compiling udunits2
only merge after: https://github.com/ministryofjustice/analytics-platform-cran-proxy/pull/3 is merged and a v0.3.0 release is tagged
> Cran-Proxy: Bump version of base image

- charts/cran-proxy/Chart.yaml
- charts/cran-proxy/values.yaml
This new image pins the version of the Prometheus client to one that is
compatible with sanic-prometheus
> Cran-Proxy: Bump docker image version

- charts/jupyter-lab/CHANGELOG.md
- charts/jupyter-lab/Chart.yaml
- charts/jupyter-lab/templates/deployment.yaml
- charts/jupyter-lab/values.yaml
The new docker image,
revert previous change setting uid as 1001 at the pod level.
We have put this back into the image as we found a couple of issues with this approach
> Jupyter-lab: Bump docker image version

- charts/kube2iam/CHANGELOG.md
- charts/kube2iam/Chart.yaml
- charts/kube2iam/templates/daemonset.yml
- charts/kube2iam/values.yaml
From : https://github.com/jtblin/kube2iam#aws-sts-endpoint-and-regions
> STS also has regional endpoints which can only be explicitly used
> programatically. The use of a regional sts endpoint can reduce the
> latency for STS requests
By passing the `sts_region` value to the helm chart, kube2iam will use the regional endpoint
which can improve STS requests' latency.
By defaul kube2iam **will not** use regional STS endpoint.
> kube2iam 1.1.2: Added support for regional STS endpoint

- charts/rbac/CHANGELOG.md
- charts/rbac/Chart.yaml
- charts/rbac/README.md
- charts/rbac/templates/kubelet-api.yaml
- charts/rbac/values.yaml
[Trello](https://trello.com/c/YNDTzEIx)
When we became aware of this[ vulnerability](https://medium.com/handy-tech/analysis-of-a-kubernetes-hack-backdooring-through-kubelet-823be5c3d67c)
We decided to disable anonymous auth.  However, this prevents Prometheus via the node exporter and possibly other components from successfully
querying the API to gather metrics.
Enabling [RBAC](https://kubernetes.io/docs/reference/access-authn-authz/rbac/) ensures that all workloads, cluster or user-defined
should use a serviceaccount.  Serviceaccounts use auth tokens when making requests to the API. Disabling anonymous auth on the kubelet API and setting it to use these tokens to authenticate and a clusterrole for authorisation mitigates the vulnerability mentioned above while allowing the workloads …
> RBAC: Kubelet

- charts/cran-proxy/Chart.yaml
- charts/cran-proxy/values.yaml
also bumps chart version; this new image makes more portable binary packages
> Cran-Proxy v0.4.0: Bump image version

- charts/cran-proxy/Chart.yaml
- charts/cran-proxy/templates/deployment.yaml
- charts/cran-proxy/values.yaml
This new image (v0.5.0) allows an environment variable called `PASSIVE`
which this chart is updated to support
> Cran-Proxy: Update image to v0.5.0

- charts/cluster-autoscaler/CHANGELOG.md
- charts/cluster-autoscaler/Chart.yaml
- charts/cluster-autoscaler/values.yaml
[Trello](https://trello.com/c/FTCJKlbh)
Cluster autoscaler is version specific.  From K8s 1.12 the cluster autoscaler version lock steps.  For now, I am upgrading the cluster autoscaler image to `gcr.io/google-containers/cluster-autoscaler:v1.3.5`
See: https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler#releases
**Note** Already deployed
> Upgrade Cluster AutoScaler

- charts/images-prepuller/.helmignore
- charts/images-prepuller/CHANGELOG.md
- charts/images-prepuller/Chart.yaml
- charts/images-prepuller/README.md
- charts/images-prepuller/templates/NOTES.txt
- charts/images-prepuller/templates/_helpers.tpl
- charts/images-prepuller/templates/configmap.yaml
- charts/images-prepuller/templates/deamonset.yaml
- charts/images-prepuller/values.yaml
Why?
=====================================================================
Some of our Docker images are quite big and it can take some time for
them to be downloaded.
If that image was not already downloaded on that node, the first user
which spawns a tool using that docker image will have to wait more than
the usual.
This can be confusing for the users as most of the time these
tools starts relatively quickly. When this takes longer the user
perceive this delay as a symptom of "something didn't work".
This is made worse by the fact that we now have configured our
kubernetes cluster to scale up and down. This means that new
nodes could be created more often. These fresh nodes
will not have the most used Docker images yet.
How does it work? …
> images-prepuller: Pre-pull/caches images on kubernetes nodes

- charts/rbac/CHANGELOG.md
- charts/rbac/Chart.yaml
- charts/rbac/README.md
- charts/rbac/templates/generic-support.yaml
- charts/rbac/values.yaml
These users will be able to read/list the main kubernetes resources:
- ingresses
- services
- deployments
- pods
- cronjobs
- jobs
These users will have these permissions across the whole cluster, so
in all namespaces.
**NOTE**: Users will not be able to edit these resources (or at least
not at this stage) and they will not be able to read secrets or
configmaps.
Ticket: https://trello.com/c/LsQcIL12
> rbac: Added "generic-support" group with read-only access to main resources

- charts/rbac/README.md
- charts/rbac/templates/app-support.yaml
- charts/rbac/values.yaml
- added `--namespace` param to install/upgrade command so that
if the user is on a different namespace they'll not accidentally
install the helm chart in the wrong namespace
- added `--dry-run` flag, so that users will need to check helm
output before actually installing the helm chart
- fixed typo in `appSupport` value: `desciprtion` => `description`
> rbac: Improved install command in README and fixed value key typo

- charts/webapp/CHANGELOG.md
- charts/webapp/values.yaml
Apps will get the new auth-proxy, bringing this change: https://github.com/ministryofjustice/analytics-platform-auth-proxy/pull/80
I tested this version here: https://kpi-s3-proxy.apps.alpha.mojanalytics.xyz/
> Update auth proxy to latest

- charts/unidler/CHANGELOG.md
- charts/unidler/Chart.yaml
- charts/unidler/templates/clusterrole.yaml
Core API group name is `""` not `"core"` ☹️
> Fix unidler clusterrole

- charts/cpanel/CHANGELOG.md
- charts/cpanel/Chart.yaml
- charts/cpanel/templates/cluster-role.yaml
This is needed to get the hostname for an app to provide a link on the app details page.
This can be removed when webapps all have a `host` label.
> Give control panel API access to list and read ingresses

- charts/idler/CHANGELOG.md
- charts/idler/Chart.yaml
- charts/idler/templates/clusterrole.yaml
Idler needs permission to read and patch Services in the new style of idling.
> Grant idler access to read and patch services

- charts/airflow-k8s/CHANGELOG.md
- charts/airflow-k8s/Chart.yaml
- charts/airflow-k8s/templates/hooks/init-airflow-ns-hook.yml
Chart installation when chart was previously installed and purged.
This was caused by `init-airflow-ns` job that annotate the
`airflow` namespace.
Techical details: The problem was that the `Job` created on new
install (`else` statement) was not idempotent because it was
missing the `--overwrite` flag (which the `if` block had).
I've simplified the init job template to factor all the
common parts and have a smaller `if` just for the
`helm.sh/hook` annotation.
> airflow-k8s 0.0.9: Fixed failing init job when re-installing

- charts/idler/CHANGELOG.md
- charts/idler/Chart.yaml
- charts/idler/templates/clusterrole.yaml
- charts/unidler/CHANGELOG.md
- charts/unidler/Chart.yaml
- charts/unidler/templates/clusterrole.yaml
Idler had `read` instead of `get`
Idler had permissions on ingresses that are no longer used
Unidler had several unused permissions
> Update idler/unidler clusterrole permissions

- charts/airflow-k8s/CHANGELOG.md
- charts/airflow-k8s/Chart.yaml
- charts/airflow-k8s/README.md
- charts/airflow-k8s/templates/create-nfs-dirs.yml
- charts/airflow-k8s/templates/git-sync-deployment.yml
- charts/airflow-k8s/templates/hooks/init-airflow-ns-hook.yml
- charts/airflow-k8s/templates/scheduler-deployment.yml
- charts/airflow-k8s/templates/webserver-deployment.yml
- charts/airflow-k8s/values.yaml
- [Bumped Airflow version/docker tag to `1.10.2`](https://github.com/ministryofjustice/analytics-platform-airflow-docker-image/pull/3)
- Bumped `bitnami/redis` docker image from `4.0.10-debian-9` to
`4.0.12-debian-9-r46`
- Change redis image pull policy from `Always` to `IfNotPresent` (as we're not using `latest` 
therefore image with a given tag shouldn't change!)
- Added `appVersion` to chart metadata to improve visibility of which Airflow version the chart is using.
Ticket: https://trello.com/c/7yqU330n/144-upgrade-airflow-version-and-its-redis-image-version
> airflow-k8s 0.1.0: Bumped Airflow to 1.10.2

- charts/airflow-k8s/CHANGELOG.md
- charts/airflow-k8s/Chart.yaml
- charts/airflow-k8s/templates/configmap.yml
- charts/airflow-k8s/values.yaml
- Fixed problem where some of the authentication requests were done over
**non-secure** HTTP connection.
- added `airflow.config.webserver.enable_proxy_fix` which
by default is `True` but can be changed if necessary
- See:
- Airflow issue: [`AIRFLOW-3137`](https://issues.apache.org/jira/browse/AIRFLOW-3137)
- Airflow fix: [`PR #3983`](https://github.com/apache/airflow/pull/3983)
**NOTE**: You should only enable the `ProxyFix` middleware when running
Airflow behind a trusted proxy (AWS ELB, nginx, etc.).
Ticket: https://trello.com/c/6AbABA6a/161-make-sure-airflow-is-always-using-https
> airflow-k8s 0.1.1: Fix for some requests made over **non-secure** HTTP

- charts/jupyter-lab/CHANGELOG.md
- charts/jupyter-lab/Chart.yaml
- charts/jupyter-lab/values.yaml
New version of the image avoids slow startup problems for jupyter users.
> Jupyter Lab: Update docker image tag

- charts/rstudio/CHANGELOG.md
- charts/rstudio/Chart.yaml
- charts/rstudio/templates/deployment.yml
- charts/rstudio/values.yaml
- Version of RStudio image with conda (r3.5.1-py3.7-conda)
- it doesn't point at the cran proxy
- does initial setup in an init container
- has a rstudio conda environment
- maintains support for projects still using packrat
- can point to an older image that doesn't support init by setting `rstudio.image.init` to false
> Rstudio v1.6.0: Switch to conda rstudio image

- charts/fluentd/CHANGELOG.md
- charts/fluentd/Chart.yaml
- charts/fluentd/templates/daemonset.yaml
There were no logs in Elasticsearch for workloads scheduled on highmem
nodes.
The fluentd log shipping addon/`daemonset` could not tolerate the highmem node's taint and therefore could not
be scheduled to the highmem node when it was provisioned.
- Added toleration for highmem node's taint
- Added `operator` context to k8s master toleration
- _Deployed_ and tested
[Saved_kibana_search](https://kibana.services.alpha.mojanalytics.xyz/app/kibana#/discover/cda3f6e0-3e88-11e9-bdc5-377aef7b1bc9?_g=())
> Schedule to High Memory Nodes

- charts/prometheus-resources/CHANGELOG.md
- charts/prometheus-resources/Chart.yaml
- charts/prometheus-resources/README.md
- charts/prometheus-resources/templates/_helpers.tpl
- charts/prometheus-resources/templates/analytics-rules.yaml
- charts/prometheus-resources/templates/clusterrole-psp.yaml
- charts/prometheus-resources/templates/configmap.yaml
- charts/prometheus-resources/templates/deployment.yaml
- charts/prometheus-resources/templates/ingress.yaml
- charts/prometheus-resources/templates/psp-auth-proxy.yaml
- charts/prometheus-resources/templates/rolebinding-psp.yaml
- charts/prometheus-resources/templates/secrets.yaml
- charts/prometheus-resources/templates/service-account.yaml
- charts/prometheus-resources/templates/service-monitor.yaml
- charts/prometheus-resources/templates/service.yaml
- charts/prometheus-resources/values.yaml
Relates to: [PR](https://github.com/ministryofjustice/analytics-platform-config/pull/114)
- Initial commit
- Migrated our deployment from [CoreOS's deprecated chart](https://github.com/coreos/prometheus-operator/tree/master/helm) to [Helm stable repo chart](https://github.com/helm/charts/tree/master/stable/prometheus-operator)
- Secured [Prometheus](https://prometheus.services.dev.mojanalytics.xyz) and [AlertManager](https://alertmanager.services.dev.mojanalytics.xyz) front-ends with [auth-proxy](https://github.com/ministryofjustice/analytics-platform-auth-proxy)
- Migrated Dashboard templates to Grafana 5.4.x spec
- Migrated Rules, Alerts and Dashboards from the previous deployment
- Added `PodSecurityPolicy` in preparation for [Trello](https://trello.com/c/0mfKXhjp)
> Prometheus Chart Migration

- charts/unidler/CHANGELOG.md
- charts/unidler/Chart.yaml
- charts/unidler/templates/deployment.yaml
- charts/unidler/values.yaml
New version of unidler which should fix [Issue #95]:
"Unidler giving misleading messages", specifically it sometimes shows a
strange `undefined` JS error. We think this was caused by the unidler
erroneously updating the app Service too early. If then the client
for whatever reason makes another request to `/events` this will go to
the actual app which doesn't have a `/events` endpoint.
Other improvements:
- users receive more updates as their app is being unidled
- fixed space between text and image
- unidler logs more useful things now
- other internal refactorings which shouldn't be user-facing
- Don't set `INGRESS_CLASS_NAME` variable as unidler doesn't use it anymore
[Issue #95]: https://github.com/ministryofjustice/analytics-platform/issues/95
> unidler v3.2.0: Fix for `undefined` error

- charts/concourse-org-pipeline/CHANGELOG.md
- charts/concourse-org-pipeline/Chart.yaml
- charts/concourse-org-pipeline/values.yaml
- charts/webhook-dispatcher/Chart.yaml
- charts/webhook-dispatcher/values.yaml
Changed release versions of webhook-dispatcher and org-scanner releases
This is to allow us to use the command line with parameters for concourse
> Update webhook dispatcher and org scanner image release scanner.

- charts/webapp/migrations/upgrade_releases.sh
__Long running issue__: `received message larger than max (6645791 vs. 4194304)`
Due to the number of releases deployed to the cluster helm exceeds it's
download cache limit.
- Workaround by using the namespace flag
- Upgrade helm version
> WebApp Migration Helm List

- charts/unidler/CHANGELOG.md
- charts/unidler/Chart.yaml
- charts/unidler/values.yaml
Bumped unidler to version `v0.2.1`.
**Better handling of connection errors and wording tweaks**
- treat connection errors differently: e.g. don't show undefined message and don't close EventSource to allow recover
- tell the user that wait for the deployment could take minutes
- don't send low-level k8s error to user when Service.Patch() failed
- improved logging messages to be more accurate of what actually happened
[See unidler Release/PR](https://github.com/ministryofjustice/analytics-platform-go-unidler/releases/tag/v0.2.1).
> unidler v3.2.1: Fix `undefined` error and improves wording

- charts/webapp/CHANGELOG.md
- charts/webapp/Chart.yaml
- charts/webapp/values.yaml
It appears that the increased cpu shares for webapps has not been enough
to settle the throttling alerts.  I’m going to increase the limits
further to 1 core.
- Increased cpu shares for fluentd. Requests and limits from 200m to 500m and 500m to 1 core respectively
> FluentD Resources WebApp

- charts/jupyter-lab/CHANGELOG.md
- charts/jupyter-lab/Chart.yaml
- charts/jupyter-lab/README.md
- charts/jupyter-lab/templates/NOTES.txt
- charts/jupyter-lab/templates/_helpers.tpl
- charts/jupyter-lab/templates/configmap-bash-profile.yaml
- charts/jupyter-lab/templates/deployment.yaml
- charts/jupyter-lab/templates/ingress.yaml
- charts/jupyter-lab/templates/job-bash-profile.yaml
- charts/jupyter-lab/templates/secrets.yaml
- charts/jupyter-lab/templates/service.yaml
- charts/jupyter-lab/values.yaml
- charts/rstudio/CHANGELOG.md
- charts/rstudio/Chart.yaml
- charts/rstudio/README.md
- charts/rstudio/templates/NOTES.txt
- charts/rstudio/templates/_helpers.tpl
- charts/rstudio/templates/deployment.yml
- charts/rstudio/templates/ingress.yml
- charts/rstudio/templates/secrets.yml
- charts/rstudio/templates/service.yml
RStudio 1.7.0: Added `host` label to all resources
===================================
- added `host=` label to everything, this will help simplify the idler
- don't set unused `TOOLS_DOMAIN` environment variable
- simplified installation/upgrade instructions in README
- added `host` template to remove duplication
- removed unused `name` template
Jupyter 0.2.0: Added `host` label to all resources
===================================
- added `host=` label to everything, this will help simplify the idler
- simplified installation/upgrade instructions in README
- added `host` template to remove duplication
- added NOTES.txt so that jupyter URL will be shown after installation
> Added `host` label to all idleable tools (RStudio and Jupyter)

- charts/priority-classes/.helmignore
- charts/priority-classes/Chart.yaml
- charts/priority-classes/README.md
- charts/priority-classes/templates/system-priority-class.yaml
- charts/priority-classes/values.yaml
[Trello](https://trello.com/c/Ay2ryNvC)
Adding a priority class to be referenced by system pods
We want some pods (particularly those that handle log and metrics aggregation) to be considered a higher priority by the scheduler.
We had an instance where a node was experiencing resource contention and
a `daemonset` controlled pod was left in a `pending` state after the pod
restarted.  `Daemonset` pods have the `nodeName` field set so if the specified node has no room to
accommodate the workload then the Scheduler has no choice but to wait for
the specified node to become available.
A pod referencing the `system` priority class will always be scheduled.
Even if it means evicting other lower priority pods. Pods that have no
priority set has a priority of `0`.
> Pod Priority Classess

- charts/fluentd/CHANGELOG.md
- charts/fluentd/Chart.yaml
- charts/fluentd/templates/daemonset.yaml
- charts/fluentd/values.yaml
[Trello](https://trello.com/c/Ay2ryNvC)
- Added `priorityClassName` reference to system `PriorityClass`
- Increased burstable cpu limit from `500m` to 1 cpu
- Changed apiVersion for `daemonset`
> FluentD Pod Priority Class

- charts/airflow-k8s/CHANGELOG.md
- charts/airflow-k8s/Chart.yaml
- charts/airflow-k8s/templates/git-sync-deployment.yml
- charts/airflow-k8s/templates/secrets.yml
- charts/airflow-k8s/values.yaml
Add git sync repo for ariflow dags to a kube secret so we can add the github access token to pull private repos - specifically making the `airflow-dags` repo private
> Add git sync repo for ariflow dags to a kube secret

- charts/unidler/CHANGELOG.md
- charts/unidler/Chart.yaml
- charts/unidler/values.yaml
- Removed #/6 "progress" messages as confusing (for some users)
- Better handling of "nonexistent key" error when patching Service to avoid
showing "Failed to redirect back your app" when we can safely recover.
- when unidling an app which has annotation with unidled number of replicas
of `0`, assume this is a mistake and set number of replicas to `1`.
See PRs:
- https://github.com/ministryofjustice/analytics-platform-go-unidler/pull/7
- https://github.com/ministryofjustice/analytics-platform-go-unidler/pull/8
> unidler v3.2.2: Less errors reaching the user and UX tweaks

- charts/jupyter-lab/CHANGELOG.md
- charts/jupyter-lab/Chart.yaml
- charts/jupyter-lab/templates/deployment.yaml
- charts/jupyter-lab/values.yaml
upgrade to auth proxy that supports _tunneling_. Add environment variable to the
deployment to enable the feature.
> Jupyter-lab: Upgrade auth proxy image

- charts/unidler/CHANGELOG.md
- charts/unidler/Chart.yaml
- charts/unidler/values.yaml
**NOTE**: This is a breaking change as the unidler now uses the `host` labels
to retrieve the resources to change. But these labels need to be there.
So not exactly retro-compatible.
- use `host` labels to find Ingress, Deployment, etc...
- use `mojanalytics.xyz/replicas-when-unidled` annotation instead of old
`mojanalytics.xyz/idled-at` which was trying to do too many things at once
**SEE**:
- [unidler changes](https://github.com/ministryofjustice/analytics-platform-go-unidler/pull/9)
- [migration to add labels](https://github.com/ministryofjustice/analytics-platform-ops/pull/266)
**Ticket**: https://trello.com/c/NMpN8B1j/132-add-host-label-to-all-idleable-apps-tools
> unidler v4.0.0: Bumped unidler version to `v1.0.0`

- charts/webapp/CHANGELOG.md
- charts/webapp/Chart.yaml
- charts/webapp/templates/fluentd-configmap.yml
- charts/webapp/values.yaml
Upgrading image to make use of better error handling features, log
output and compatibility with elasticsearch `6.x`.
- Setting target `target_type_key` is more explicit and means the
elasticsearch plugin won't need to fall through the stack or error out to determine the
indexing type
- __Newwer Feature__: `log_es_400_reason` means we get log output on why
Elasticsearch returned a `400: bad request` without having to set log to
`DEBUG`
- Removed record transformer `types` key because it's not needed
> WebApp: FluentD Upgrade

- charts/webapp/CHANGELOG.md
- charts/webapp/Chart.yaml
- charts/webapp/templates/fluentd-configmap.yml
Since upgrading `FluentD` does not always auto negotiate TLS
- Added `ssl_version TLSv1_2` to output configuration
> FluentD Upgrade cipher version

- charts/idler/CHANGELOG.md
- charts/idler/Chart.yaml
- charts/idler/README.md
- charts/idler/templates/cronjob.yaml
- charts/idler/values.yaml
- Use `idler` to `v1.0.0`:
- adds `mojanalytics.xyz/replicas-when-unidled` annotation with number of
replicas desired at the time of udling. This is used by `unidler`
- `mojanalytics.xyz/idled-at` only contains time when app was idled,
nothing else
- renamed env var `RSTUDIO_ACTIVITY_CPU_THRESHOLD` =>
`CPU_ACTIVITY_THRESHOLD`
- internal refactorings
- `labelSelector` defaults to `mojanalytics.xyz/idleable=true` now
(in `idler`)
- See PR: ministryofjustice/analytics-platform-idler#68
- added `app=$RELEASE_NAME` to job's pods so that we can see logs and
investigate things much more easily
- `labelSelector` defaults to `mojanalytics.xyz/idleable=true` now (in helm
chart)
- `logLevel` defaults to `DEBUG`. We want to see what's going on unless
we explicit silence it for whatever reason.
> idler 2.0.0: bumped idler tag to `v1.0.0`

- charts/rbac/CHANGELOG.md
- charts/rbac/Chart.yaml
- charts/rbac/templates/generic-support.yaml
- Allow __generic-support__ users to list namespaces. This is to make their
life easier as they'll find the right namespace without necessarily go
through the Control Panel. They can already read and list pods so this doesn't
give support people much more power.
- Allow __generic-support__ users to read pods logs
Ticket: https://trello.com/c/meCj3EJ6
> rbac 0.3.0: `generic-support` users can read namespaces and pods logs

- charts/airflow-sqlite/.helmignore
- charts/airflow-sqlite/CHANGELOG.md
- charts/airflow-sqlite/Chart.yaml
- charts/airflow-sqlite/README.md
- charts/airflow-sqlite/templates/_env.yml
- charts/airflow-sqlite/templates/_helpers.tpl
- charts/airflow-sqlite/templates/configmap.yml
- charts/airflow-sqlite/templates/ingress.yml
- charts/airflow-sqlite/templates/scheduler-deployment.yml
- charts/airflow-sqlite/templates/secrets.yml
- charts/airflow-sqlite/templates/service-account.yml
- charts/airflow-sqlite/templates/service.yml
- charts/airflow-sqlite/templates/webserver-deployment.yml
- charts/airflow-sqlite/values.yaml
- charts/cpanel/CHANGELOG.md
- charts/cpanel/Chart.yaml
- charts/cpanel/values.yaml
- charts/init-user/CHANGELOG.md
- charts/init-user/Chart.yaml
- charts/init-user/templates/namespace.yml
- charts/jupyter-lab/CHANGELOG.md
- charts/jupyter-lab/Chart.yaml
- charts/jupyter-lab/templates/deployment.yaml
Add a helm chart for airflow-sqlite.
This is so the users can test dags running as their own user before merging and releasing them.
This will be run on demand by users via the control panel. The chart will run airflow using sqlite as the database in the users kubernetes namespace.
The users home directory will be mounted and airflow will use `/home/username/airflow/dags` as the dags directory.
> Add airflow-sqlite helm chart

- charts/airflow-sqlite/CHANGELOG.md
- charts/airflow-sqlite/Chart.yaml
- charts/airflow-sqlite/values.yaml
- charts/jupyter-lab/CHANGELOG.md
- charts/jupyter-lab/Chart.yaml
- charts/jupyter-lab/values.yaml
- charts/webapp/CHANGELOG.md
- charts/webapp/Chart.yaml
- charts/webapp/values.yaml
Bumped `auth-proxy` image tag to [`v2.1.0`](https://github.com/ministryofjustice/analytics-platform-auth-proxy/releases/tag/v2.1.0) in the following helm charts:
- `charts/airflow-sqlite`
- `jupyter-lab`
- `webapp`
The proxy doesn't run as `root` anymore.
> `auth-proxy` don't run as root

- charts/pod-cleaner/.helmignore
- charts/pod-cleaner/CHANGELOG.md
- charts/pod-cleaner/Chart.yaml
- charts/pod-cleaner/README.md
- charts/pod-cleaner/files/pod_cleaner.sh
- charts/pod-cleaner/templates/NOTES.txt
- charts/pod-cleaner/templates/_helpers.tpl
- charts/pod-cleaner/templates/configmap.yaml
- charts/pod-cleaner/templates/cronjob.yaml
- charts/pod-cleaner/templates/role.yaml
- charts/pod-cleaner/templates/rolebinding.yaml
- charts/pod-cleaner/templates/serviceaccount.yaml
- charts/pod-cleaner/values.yaml
CronJob which deletes old pods in "Succeeded" and "Failed" phase after a
certain number of days.
See kubernetes documentation on phases: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase
Ticket: https://trello.com/c/i1Nxclu3/197-airflow-remove-superseded-pods
> pod-cleaner 0.0.1: Initial release

- charts/pod-cleaner/CHANGELOG.md
- charts/pod-cleaner/Chart.yaml
- charts/pod-cleaner/README.md
- charts/pod-cleaner/templates/NOTES.txt
- charts/pod-cleaner/templates/cronjob.yaml
- charts/pod-cleaner/values.yaml
When a `Pod` fails to start because for example the image cannot be pulled
the `Pod` will be in `Pending` phase.
It makes sense to delete old pods which are failing to start.
> pod-cleaner 0.1.0: Also delete `Pending` pods

- charts/webapp/values.yaml
New auth proxy version can now tell the webapp the email address of the logged
in user via the `USER_EMAIL` header.
This header will not be set unless authentication is enabled
> Webapp: Bump Auth Proxy Version

- charts/webapp/CHANGELOG.md
- charts/webapp/Chart.yaml
- charts/webapp/values.yaml
`gcr.io/google-containers/fluentd-elasticsearch` has been deprecated in
favour of `gcr.io/fluentd-elasticsearch/fluentd`.
Application versions remain unchanged
- Changed image repo from `gcr.io/google-containers/fluentd-elasticsearch` to `gcr.io/fluentd-elasticsearch/fluentd`
- Changed __fluentd__ image tag from `v2.4.0` to `v2.5.0`
> FluentD Update Repository

- charts/jupyter-lab/CHANGELOG.md
- charts/jupyter-lab/Chart.yaml
- charts/jupyter-lab/values.yaml
- charts/rstudio/CHANGELOG.md
- charts/rstudio/Chart.yaml
- charts/rstudio/values.yaml
- charts/webapp/CHANGELOG.md
- charts/webapp/Chart.yaml
- charts/webapp/values.yaml
This commit updates the Jupyter / Rstudio / Webapp charts to use the latest
versions of the proxy they use.
In Rstudio's case this is v2.0.0 of rstudio-auth-proxy, and for the others it is
`v3.0.0` of the generic auth proxy
> Bump Auth Proxies for Jupyter / Rstudio / Webapp charts

- charts/rstudio/migrations/set_rstudio_image_tag.sh
Allow user to restrict namespaces it works on and the label selector, app, image
names by setting environment variable before executing it.
Also makes it much more verbose about what it's doing.
> Rstudio: Make migration script more configurable

- charts/rstudio/CHANGELOG.md
- charts/rstudio/Chart.yaml
- charts/rstudio/README.md
- charts/rstudio/templates/deployment.yml
- charts/rstudio/values.yaml
RStudio is the only application not using our [generic auth-proxy].
RStudio was using a special proxy which set an authentication header.
This commit attempts to disable the RStudio authentication.
By doing so we can use the plain auth proxy instead.
NOTE: The configuration for the proxy was copied and tweaked from the
jupyter-lab helm chart.
[generic auth-proxy]: https://github.com/ministryofjustice/analytics-platform-auth-proxy
Ticket: https://trello.com/c/5twZHrb4/215-try-to-replace-custom-rstudio-auth-proxy-with-our-usual-generic-one
**TODO**
> rstudio: Attempt to use generic auth-proxy

- charts/webapp/CHANGELOG.md
- charts/webapp/Chart.yaml
- charts/webapp/values.yaml
Reverted use of `X-Forwarded-For` (but working for websockets)
> webapp 1.4.1: Use auth-proxy `v4.0.1`

- charts/rstudio/CHANGELOG.md
- charts/rstudio/Chart.yaml
- charts/rstudio/values.yaml
Bumped `auth-proxy` to version [`v4.0.1`](https://github.com/ministryofjustice/analytics-platform-auth-proxy/releases/tag/v4.0.1).
This version of the proxy reads the `X-Forwarded-For` header
but fixes the problem for websockets not able to read the headers.
> rstudio 2.0.1: Bumped auth-proxy image tag

- charts/airflow-sqlite/CHANGELOG.md
- charts/airflow-sqlite/Chart.yaml
- charts/airflow-sqlite/templates/deployment.yml
- charts/airflow-sqlite/values.yaml
- charts/jupyter-lab/CHANGELOG.md
- charts/jupyter-lab/Chart.yaml
- charts/jupyter-lab/templates/deployment.yaml
- charts/jupyter-lab/values.yaml
Bumped `auth-proxy` to version [`v4.0.1`](https://github.com/ministryofjustice/analytics-platform-auth-proxy/releases/tag/v4.0.1).
This version removes support for `NICKNAME_RE` and replaces it with
a simple equality check with the `USER` environment variable.
> Bumped auth-proxy tag in airflow-sqlite/jupyter-lab

- charts/network-policies/.helmignore
- charts/network-policies/CHANGELOG.md
- charts/network-policies/Chart.yaml
- charts/network-policies/README.md
- charts/network-policies/templates/NOTES.txt
- charts/network-policies/templates/_helpers.tpl
- charts/network-policies/templates/hooks/label-ingress-controller-ns.yaml
- charts/network-policies/templates/network-policies.yaml
- charts/network-policies/templates/tests-permissions.yaml
- charts/network-policies/templates/tests/traffic-from-ingress-allowed.yaml
- charts/network-policies/templates/tests/traffic-from-pods-in-ns-blocked.yaml
- charts/network-policies/values.yaml
Initial release of helm chart with `NetworkPolicy` resources.
This currently contains only policies to restrict traffic between
webapps' pods but we may add more network policies later (that's why
in the README the installation command install this helm chart
in `default`).
Once this is installed a pod in the `apps-prod` namespace (configurable)
would not be able to talk with other pods in that namespace.
Only traffic allowed will be traffic from the Ingress controller's pod
in the `default` namespace (again, configurable in case these will
run somewhere).
Part of ticket: https://trello.com/c/z0H0xygD/227-prevents-webapp-to-be-able-to-talk-with-each-other
> network-policies 0.2.0: Restrict traffic to apps' pods

- charts/idler/CHANGELOG.md
- charts/idler/Chart.yaml
- charts/idler/values.yaml
- Fixed idling problems caused by some k8s resouces in an inconsistent
state. This is achieved by patching them using strategic merge instead
of JSONPatch.
- Also made the idling process more robust by catching all exceptions,
logging them and continuing instead of interrupting the idling of the
subsequent tools.
NOTE: The process will still return a non-zero status code so we know
idling of some of the tools didn't work.
Idler PR: https://github.com/ministryofjustice/analytics-platform-idler/pull/101
Part of ticket: https://trello.com/c/vr4LPcde/241-investigate-fix-idling-unidling-problems-caused-by-k8s-cluster-upgrade-new-version-of-k8s
> idler 2.0.1: Made the idler more robust

- charts/unidler/CHANGELOG.md
- charts/unidler/Chart.yaml
- charts/unidler/README.md
- charts/unidler/values.yaml
Use new version of the unidler which uses strategic merge patch instead of
JSONPatch.
Strategic merge is more declarative and more robust. When deleting
a key which is not there it would consider that part of the patch as already
applied instead of raising an error as in the case of JSONpatch.
- [unidler PR](https://github.com/ministryofjustice/analytics-platform-go-unidler/pull/10)
- Part of ticket: https://trello.com/c/vr4LPcde/241-investigate-fix-idling-unidling-problems-caused-by-k8s-cluster-upgrade-new-version-of-k8s
> unidler v4.0.1: Use strategic merge patch instead of JSONPatch

- charts/pod-cleaner/CHANGELOG.md
- charts/pod-cleaner/Chart.yaml
- charts/pod-cleaner/templates/cronjob.yaml
Probably caused by k8s cluster upgrade
Ticket: https://trello.com/c/J5jgkueM/244-fix-pod-cleaner-permission-problem
> pod-cleaner 0.1.1: Fixed Docker permission problem

- charts/rstudio/CHANGELOG.md
- charts/rstudio/Chart.yaml
- charts/rstudio/values.yaml
RStudio release notes: https://blog.rstudio.com/2019/04/30/rstudio-1-2-release/
Ticket: https://trello.com/c/rguKYALc/214-try-to-upgrade-rstudio-docker-image-to-use-latest-version
> RStudio 1.10.0: Bumped RStudio to version 1.2

- charts/webapp/CHANGELOG.md
- charts/webapp/Chart.yaml
- charts/webapp/values.yaml
Bump auth proxy to v5.0.0 which includes the `/userinfo` endpoint
> Webapp: Bump auth-proxy version

- charts/restarter/CHANGELOG.md
- charts/restarter/Chart.yaml
- charts/restarter/README.md
- charts/restarter/templates/NOTES.txt
- charts/restarter/templates/deployment.yaml
- charts/restarter/templates/networkpolicy.yaml
- charts/restarter/templates/role.yaml
- charts/restarter/templates/rolebinding.yaml
- charts/restarter/templates/service.yaml
- charts/restarter/templates/serviceaccount.yaml
- charts/restarter/values.yaml
Internal API to restart applications in a given
namespace.
This API doesn't have an Ingress resource so it's
only accessible from within the k8s cluster (at `${RELEASE_NAME}.${NAMESPACE}.svc.cluster.local`).
Furthermore, the service account for this API is only able to list and
patch Deployments within the namespace where the chart/API is been
released to.
Part of ticket: https://trello.com/c/zb9HsZca/254-investigate-ways-to-trigger-apps-restart-when-data-changes
> restarter v0.0.1: Initial release

- charts/nfs-backup/Chart.yaml
- charts/nfs-backup/README.md
- charts/nfs-backup/templates/configmap.yml
The below directories seem to be the usual culprits that cause the nfs
backup job to either stall or fail entirely.
I don't think there is much value in backing these directories to `s3` but please shout
if you disagree.
```
.conda
miniconda3-r
.local
Git_Repos
SAT+Shapes
py-safety
.virtualenvs
comparisons
Python
```
Already deployed `(31/07/2019)`
Will check later or tomorrow to see if it had the desired effect.
> Adding exclusions to nfs backup

- charts/webapp/values.yaml
This new auth proxy version makes sure the `secure` flag is sent with the
`connect.sid` cookie.
> Webapp: Bump auth proxy version to v5.0.1

- charts/webapp/values.yaml
This changes the response code the auth-proxy sends back when user is not in the
ip_whitelist from 500 to 403
> Bump Webapp chart: v5.1.0

- charts/kibana-auth-proxy/CHANGELOG.md
- charts/kibana-auth-proxy/Chart.yaml
- charts/kibana-auth-proxy/README.md
- charts/kibana-auth-proxy/templates/deployment.yaml
- charts/kibana-auth-proxy/values.yaml
This means we don't have to maintain several auth proxies anymore
as we now use `auth-proxy` as auth proxy for all apps.
Part of ticket: https://trello.com/c/zxHetcOl/262-get-rid-of-kibana-auth-proxy
> kibana-auth-proxy 2.1.0: Use auth-proxy as a proxy

- charts/airflow-sqlite/CHANGELOG.md
- charts/airflow-sqlite/Chart.yaml
- charts/airflow-sqlite/values.yaml
- charts/jupyter-lab/CHANGELOG.md
- charts/jupyter-lab/Chart.yaml
- charts/jupyter-lab/values.yaml
- charts/kubernetes-dashboard/CHANGELOG.md
- charts/kubernetes-dashboard/Chart.yaml
- charts/kubernetes-dashboard/README.md
- charts/kubernetes-dashboard/templates/deployment.yaml
- charts/kubernetes-dashboard/values.yaml
- charts/prometheus-resources/CHANGELOG.md
- charts/prometheus-resources/Chart.yaml
- charts/prometheus-resources/templates/deployment.yaml
- charts/prometheus-resources/values.yaml
- charts/rstudio/CHANGELOG.md
- charts/rstudio/Chart.yaml
- charts/rstudio/values.yaml
- charts/webapp/CHANGELOG.md
- charts/webapp/Chart.yaml
- charts/webapp/values.yaml
This version of [`auth-proxy`](https://github.com/ministryofjustice/analytics-platform-auth-proxy) removes the non-standard `prompt=none`.
Also note that v5.2.0 introduced support for logic to log into kibana.
Charts updated:
- airflow-sqlite
- jupyter-lab
- rstudio
- webapp
**NOTE**: `kubernetes-dashboard` and `prometheus-resources` use an older
version of the proxy - we should probably update those as well:
See auth-proxy releases for more details:
- https://github.com/ministryofjustice/analytics-platform-auth-proxy/releases/tag/v5.2.1
- https://github.com/ministryofjustice/analytics-platform-auth-proxy/releases/tag/v5.2.0
> Bumped auth-proxies to v5.2.1

- charts/webapp/CHANGELOG.md
- charts/webapp/Chart.yaml
- charts/webapp/templates/ingress.yaml
This adds some pretty safe security headers to all responses by default.
This should not be a breaking change unless an app is doing something weird like
embedding itself on another site via an IFRAME
ticket: https://trello.com/c/wpEJaXXt/36-sdt-changes-based-on-zap-result
> Webapp: Add security headers by default

- charts/concourse-org-pipeline/CHANGELOG.md
- charts/concourse-org-pipeline/Chart.yaml
- charts/concourse-org-pipeline/templates/secrets.yaml
- charts/concourse-org-pipeline/values.yaml
This allows us to deploy apps that are only accessible by someone working at the
Turing Institute
https://trello.com/c/YswsWozF/295-add-ip-for-turing-institute
> Support ip range for Alan Turing Institute

- charts/cpanel/CHANGELOG.md
- charts/cpanel/Chart.yaml
- charts/cpanel/templates/_helpers.tpl
- charts/cpanel/templates/ingress.yaml
This will make the new Control Panel receive requests to `https://cpanel-master.services...`
I'm assuming the way to actually remove the old frontend is to just `helm delete` it, but let me know if you have a nicer way
> Add old cpfrontend host to ingress

- charts/rbac/CHANGELOG.md
- charts/rbac/Chart.yaml
- charts/rbac/README.md
- charts/rbac/templates/concourse-deployments.yaml
- charts/rbac/values.yaml
And bind it to the concourse-main default service account so that concourse can
report on rollout status.
https://trello.com/c/ofx66AHU/315-show-deployment-rollout-status-for-concourse-app-builds
> RBAC: Add concourse-deployments ClusterRole

- charts/fluentd/CHANGELOG.md
- charts/fluentd/Chart.yaml
- charts/fluentd/values.yaml
This modification would allow Fluentd to start shipping the following Audit logs to ES:
`auth.log` and `syslog`
> Add auth.log and syslog.log to Fluentd input

- charts/cpanel/CHANGELOG.md
- charts/cpanel/Chart.yaml
- charts/cpanel/templates/rbac-read-ingresses.yaml
- charts/cpanel/values.yaml
CP use the app ingress to determine the app URL. It seemed like it could
already list/read ingresses but it actually couldn't.
This adds a `Role`/`RoleBinding` that specifically allow the CP to do
that (only in the apps namespace)
> cpanel 2.3.0: CP permissions to read apps ingress

- charts/cpanel/CHANGELOG.md
- charts/cpanel/Chart.yaml
- charts/cpanel/values.yaml
⚠️ : Wait for [Control Panel PR](https://github.com/ministryofjustice/analytics-platform-control-panel/pull/759) to be merged before this is merged as this flag use to default to False
Part of ticket: https://trello.com/c/OXWwaZua
> cpanel 2.3.1: Removed legacy `ENABLE_K8S_RBAC` flag

- charts/jupyter-lab/CHANGELOG.md
- charts/jupyter-lab/Chart.yaml
- charts/jupyter-lab/templates/deployment.yaml
- charts/priority-classes/Chart.yaml
- charts/priority-classes/templates/system-priority-class.yaml
- charts/priority-classes/values.yaml
- charts/rstudio/CHANGELOG.md
- charts/rstudio/Chart.yaml
- charts/rstudio/templates/deployment.yml
- charts/rstudio/values.yaml
- charts/webapp/CHANGELOG.md
- charts/webapp/Chart.yaml
- charts/webapp/templates/deployment.yaml
[Trello](https://trello.com/c/sMRJcSXN)
Added Priority Classes for user workloads
Priority:
- Jupyter-Lab = 10 Million
- RStudio        = 10 Million
- WebApps     = 2  Million
User Tools and WebApp charts:
- Added `priorityClassName` to pod spec
- Updated `Deployment` APIGroup
> High Priority Workloads

- charts/rstudio/CHANGELOG.md
- charts/rstudio/Chart.yaml
- charts/rstudio/templates/deployment.yml
Unfortunately apps/v1's Deployments now needs spec.selector.matchLabels in order to work.
How did it even work before?
bug fix: https://trello.com/c/HfICQ15Y/386-add-matchselector-to-tools-charts
> Rstudio: Add `spec.selector.matchLabels` to deployment

- charts/cluster-autoscaler/CHANGELOG.md
- charts/cluster-autoscaler/Chart.yaml
- charts/cluster-autoscaler/templates/clusterrole.yaml
- charts/cluster-autoscaler/values.yaml
- Updated clusterrole api-group for replicasets
- Upgraded cluster autoscaler to lockstep version with __OLD__ dev and
alpha
> Upgrade CA: OLD dev and alpha

- charts/cluster-autoscaler/CHANGELOG.md
- charts/cluster-autoscaler/Chart.yaml
- charts/cluster-autoscaler/templates/clusterrole.yaml
- charts/cluster-autoscaler/values.yaml
Upgraded cluster autoscaler to lockstep with k8s version in new environment from `1.12.8` to `1.13.8`
> Upgrade ca new env

- charts/init-user/CHANGELOG.md
- charts/init-user/Chart.yaml
- charts/init-user/templates/role-binding.yml
- charts/rbac/CHANGELOG.md
- charts/rbac/templates/user-namespaces.yaml
- charts/rbac/values.yaml
Conversation earlier prompted the need for a read-only role on user
namespaces.
- Added __user-read__ `ClusterRole` with intent to be used primarily by the [__init-user__](../init-user) helm chart
and/or any other entity that can make use of it. i.e. `ServiceAccount` binding.
- __user-read__ `ClusterRole` scoped to read `ingresses`, `services`, `deployments`, `pods` and `configmaps`
> User Read ClusterRole

- charts/cert-manager-resources/CHANGELOG.md
- charts/cert-manager-resources/Chart.yaml
- charts/cert-manager-resources/README.md
- charts/cert-manager-resources/templates/certificate.yaml
- charts/cert-manager-resources/templates/cluster-issuer.yaml
- charts/cert-manager-resources/values.yaml
[Trello](https://trello.com/c/vK2e5D58)
Our current version of Cert Manager will be blocked by LetsEncrypt as of
1 Nov 2019.
Deploying Latest version of Cert Manager as of now (__31\10\2019__):
`0.11.0`
> Upgrade Cert Manager

- charts/priority-classes/Chart.yaml
- charts/priority-classes/templates/system-priority-class.yaml
- charts/priority-classes/values.yaml
[Trello](https://trello.com/c/sMRJcSXN)
Relates to [PR](https://github.com/ministryofjustice/analytics-platform-helm-charts/pull/389)
Our deployments of k8s are both too old and new:
- Old because they do not have stable `v1` in `scheduling.k8s.io` yet
- New because `PriorityClass` is enabled by default and the __system__ `PriorityClass` is deployed as a default to same value this chart used to set.
**Deployed to all envs**
> High Priority Workloads 2

- charts/unidler/CHANGELOG.md
- charts/unidler/Chart.yaml
- charts/unidler/README.md
- charts/unidler/templates/deployment.yaml
- charts/unidler/values.yaml
Fix for long "host" label and added `unidleKeyLabel` value to support
`UNIDLE_KEY_LABEL` configuration (unidler will stop using `host` label
in new clusters and start using `unidle-key` label)
Part of ticket: https://trello.com/c/kVT0QFqe
> unidler v4.0.3: Uses unidler `v1.0.4` (support for `unidle-key`)

- charts/cpanel/CHANGELOG.md
- charts/cpanel/Chart.yaml
- charts/cpanel/templates/job.yaml
Deployment is failing due to the migrations job requiring the SLACK_API_TOKEN environment variable.
> Pass Slack API token to CPanel migrations job

- README.md
- mention Concourse pipeline which automatically update repository
- added links to Concourse pipeline and its definition in the `concourse-pipelines` repository
- replaces `helm install` commands with `helm upgrade --install` commands which can be used to install and also upgrade
- mentioned `--debug --dry-run` flags to preview helm changes
> README: links to concourse, updated commands

- charts/webapp/CHANGELOG.md
- charts/webapp/Chart.yaml
- charts/webapp/values.yaml
See https://github.com/ministryofjustice/analytics-platform-auth-proxy/releases/tag/v5.2.2 which contains https://github.com/ministryofjustice/analytics-platform-auth-proxy/pull/166
> Update URL for crown logo on auth proxy login page

- charts/idler/CHANGELOG.md
- charts/idler/Chart.yaml
- charts/idler/README.md
- charts/idler/values.yaml
This is to reduce users' waiting time in the morning.
I've updated the default `schedule` as we currently we don't have config
files for this helm chart and it makes sense to keep installation of
this chart simple rather then require a config file.
Ticket: https://trello.com/c/6yyF8WFV
> idler 2.1.0: Run idler every Wednesday by default

- charts/webapp/CHANGELOG.md
- charts/webapp/Chart.yaml
- charts/webapp/templates/deployment.yaml
- charts/webapp/templates/fluent-bit-configmap.yml
- charts/webapp/templates/ingress.yaml
- charts/webapp/templates/secrets.yaml
- charts/webapp/templates/service-account.yaml
- charts/webapp/templates/service.yaml
This reverts commit 04cd02233449af29700e126090732fe186f75f38 (so basically I'm adding back `host` label for webapps)
The `host` label is not only used by the [*restarter* service](https://github.com/ministryofjustice/analytics-platform-restarter) but
it's also causing some webapp deployments to fail because
of a new constraint on labels in `apps/v1` which means
they can't change
SEE: [kubernetes issue on GitHub](https://github.com/kubernetes/kubernetes/issues/26202)
Ticket: https://trello.com/c/drbbqgjC
> webapp 2.3.7: Revert "webapp 2.3.5: removed unused `host` labels"

- charts/airflow-sqlite/CHANGELOG.md
- charts/airflow-sqlite/Chart.yaml
- charts/airflow-sqlite/values.yaml
- charts/jupyter-lab/CHANGELOG.md
- charts/jupyter-lab/Chart.yaml
- charts/jupyter-lab/values.yaml
- charts/kibana-auth-proxy/CHANGELOG.md
- charts/kibana-auth-proxy/Chart.yaml
- charts/kibana-auth-proxy/values.yaml
- charts/kubernetes-dashboard/CHANGELOG.md
- charts/kubernetes-dashboard/Chart.yaml
- charts/kubernetes-dashboard/values.yaml
- charts/prometheus-resources/CHANGELOG.md
- charts/prometheus-resources/Chart.yaml
- charts/prometheus-resources/values.yaml
- charts/rstudio/CHANGELOG.md
- charts/rstudio/Chart.yaml
- charts/rstudio/values.yaml
- charts/webapp/CHANGELOG.md
- charts/webapp/Chart.yaml
- charts/webapp/values.yaml
This version updates some of the dependencies, [including `handlebars` `4.7.2`](https://github.com/ministryofjustice/analytics-platform-auth-proxy/pull/214)
which fixes a security vulnerability.
See:
- https://github.com/ministryofjustice/analytics-platform-auth-proxy/releases/tag/v5.2.4
- https://github.com/ministryofjustice/analytics-platform-auth-proxy/releases/tag/v5.2.3
Updated helm charts:
- webapp
- rstudio
- jupyter-lab
- airflow-sqlite
- kibana-auth-proxy
- kubernetes-dashboard
- prometheus-resources
Part of ticket: https://trello.com/c/wUaYAyYZ
> Bumped auth-proxy to `v5.2.4`

- charts/buckets-archiver/CHANGELOG.md
- charts/buckets-archiver/Chart.yaml
- charts/buckets-archiver/README.md
- charts/buckets-archiver/templates/clusterrole.yaml
- charts/buckets-archiver/templates/clusterrolebinding.yaml
- charts/buckets-archiver/templates/cronjob.yaml
- charts/buckets-archiver/templates/serviceaccount.yaml
- charts/buckets-archiver/values.yaml
CronJob which archives S3 buckets (tagged `to-archive=true`) by moving
their data to an `archiveBucket` (e.g. `dev-archived-buckets-data`)
before deleting them.
`buckets-archiver` code in this repo: https://github.com/ministryofjustice/analytics-platform-buckets-archiver - please have a look as well, sorry for the lack of PR as it was a new repo.
The S3 bucket and the permissions for the `buckets-archiver` are created in Terraform. See PR: https://github.com/ministryofjustice/analytics-platform-ops/pull/311
https://trello.com/c/6VdNPbzz
https://github.com/ministryofjustice/analytics-platform-config/pull/190 👉
> buckets-archiver 0.0.1: Initial release

- charts/config-user/files/pre-commit
For each .ipynb file commited to a git repo. On pre-commit
Call nbstripout (https://github.com/kynan/nbstripout) 
This will remove the outputs from the file 
And then add the file to the repo
This is as part of story (https://trello.com/c/P7BRQJWC/333-strip-out-ipython-notebook-output-using-a-git-hook-for-all-users)
> Call nbstripout to remove outputs from .ipynb files

- charts/config-user/Chart.yaml
- charts/config-user/files/git-config.sh
We need to set the global git templates directory 
This will automatically copy all templates from .git-templates into per project .git
> set git global templates

- charts/config-user/Chart.yaml
- charts/config-user/files/git-config.sh
Set global git template path to ~/.git-templates and not USER_HOME (dhirajnarwanimoj).
The reason is that jupyter runs another user (jovyan) and we need to change the ~/.git-templates of that user
> set git-template path to ~/.git-templates

- charts/config-user/CHANGELOG.md
- charts/config-user/Chart.yaml
- charts/config-user/files/git-config.sh
The issue is that .git-templates was set to root and the hooks folder wasn't getting copied.
We need to chown to 1001:staff to .git-templates
> Set git global

- charts/rstudio/CHANGELOG.md
- charts/rstudio/Chart.yaml
- charts/rstudio/values.yaml
We need to set the r-studio-tag to a new tag '1.2.1335-r3.5.1-python3.7.1-conda-4'. 
This has been tested and released already on quay
> Tag r-studio-server with 1.2.1335-r3.5.1-python3.7.1-conda-4

- charts/rstudio/CHANGELOG.md
- charts/rstudio/Chart.yaml
- charts/rstudio/values.yaml
Bump version to conda-5 in order to create a new r-studio-server release
> bump version to conda-5

- charts/config-user/CHANGELOG.md
- charts/config-user/Chart.yaml
- charts/config-user/files/git-config.sh
Add -R to $GIT_TEMPLATES to set hooks as executables
I'm currently getting this warning: 
hint: The 'pre-commit' hook was ignored because it's not set as executable.
> add -R flag

- charts/config-user/CHANGELOG.md
- charts/config-user/Chart.yaml
- charts/config-user/files/pre-commit
- charts/jupyter-lab/values.yaml
- charts/rstudio/values.yaml
Add Path to both jupyter and r-studio nbstripout PATHS to git pre-commit hook rather than individual docker image.
In dev nbstripout gets installed in ~/.local/bin and in alpha in /opt/conda/bin.
> Add path to pre-commit hook

- charts/concourse-admin-team/README.md
- charts/concourse-org-pipeline/README.md
Because we normally upgrade these days. Easiest to provide a command for both.
Also put in a more realistic path to the config, so it is clearer.
> Update chart deploy commands for upgrading OR installing

- charts/rstudio/CHANGELOG.md
- charts/rstudio/Chart.yaml
- charts/rstudio/values.yaml
Background
nbstripout is a tool that strips outputs from Jupyter notebooks (https://github.com/kynan/nbstripout)
We use it as a pre-commit hook to remove outputs from Jupyter notebooks before they are committed to Github as they may contain sensitive details.
Currently, nbstripout is installed via pip in the default R Studio image.
This causes issues with the initialisation of new conda environments which stops R Studio from starting up.
We have also issues with R Studio startup due to some files in the ~/.conda/env/rstudio/bin directory that have incorrect permissions. This appears to be because we are now using a later version of conda (4.8.3) than the latest stable R Studio image which is using conda 4.7.9.
Changes
This PR updates the default image tag for R Studio to use release …
> Update R studio chart to use image tag that installs nbstripout with conda

- charts/rstudio/README.md
* I had problems doing upgrades that I'm keen for others to avoid using delete --purge.
* Seems clearer to mention the --version param than write the whole command again
* Chart resource names have changed from rstudio-USERNAME to USERNAME-rstudio
> Improve RStudio upgrade commands

- charts/airflow-sqlite/CHANGELOG.md
- charts/airflow-sqlite/Chart.yaml
- charts/airflow-sqlite/values.yaml
- charts/jupyter-lab/CHANGELOG.md
- charts/jupyter-lab/Chart.yaml
- charts/jupyter-lab/values.yaml
- charts/kibana-auth-proxy/CHANGELOG.md
- charts/kibana-auth-proxy/Chart.yaml
- charts/kibana-auth-proxy/values.yaml
- charts/kubernetes-dashboard/CHANGELOG.md
- charts/kubernetes-dashboard/Chart.yaml
- charts/kubernetes-dashboard/values.yaml
- charts/prometheus-resources/CHANGELOG.md
- charts/prometheus-resources/Chart.yaml
- charts/prometheus-resources/values.yaml
- charts/rstudio/CHANGELOG.md
- charts/rstudio/Chart.yaml
- charts/rstudio/values.yaml
- charts/webapp/CHANGELOG.md
- charts/webapp/Chart.yaml
- charts/webapp/values.yaml
This is a maintenance release of the `auth-proxy` which upgrades
some of its dependencies.
Few of these new dependencies also fix some potential security
vulnerabilities.
This commit updates the following helm charts to use this new version,
all the helm charts were using a recent version of the `auth-proxy`
of the `v5.2.x` series so this change should not - in theory - break any
of the existing helm charts in theory:
- airflow-sqlite
- jupyter-lab
- kibana-auth-proxy
- kubernetes-dashboard
- prometheus-resources
- rstudio
- webapp
See `auth-proxy` Release Notes for more info: https://github.com/ministryofjustice/analytics-platform-auth-proxy/releases/tag/v5.2.6
Part of ticket: https://trello.com/c/wTQiRlcJ
> Use v5.2.6 of auth-proxy in helm charts

- charts/prometheus-resources/Chart.yaml
- charts/prometheus-resources/values.yaml
Add kubernetesSystem monitoring checks, but with custom timing for KubeNodeNotReady which is hardcoded in the public chart
> Trello-564-alert-settings

- charts/README.md
We use metrics-server since Sept 2018
Metrics-server chart install is documented here:
https://github.com/ministryofjustice/analytics-platform-config/blob/master/chart-env-config/alpha/metrics-server.yaml
> Remove heapster

- charts/priority-classes/Chart.yaml
- charts/priority-classes/values.yaml
At the moment the concourse worker pods run with a default priorityclass (with a priority of 0).
The workers in the current version of concourse don't seem to be very stable when they are moved to different nodes often (as they have to retire as workers before they can restart and that doesn't always work). Increasing the priority of the concourse pods should mean they are less likely to be scheduled to a different node once they are started.
This PR will create a new priority class named concourse with a priority of 20 million.
It also removes a commented out priorityclass.
> Add priority class for concourse workers

- charts/concourse/CHANGELOG.md
- charts/concourse/Chart.yaml
- charts/concourse/templates/worker-statefulset.yaml
- charts/concourse/values.yaml
We have seen issues with the Concourse workers pods failing on a regular basis due to 
- the PVCs that they use to cache config filling up
- workers failing to retire cleanly
The reason that the PVCs seem to be filling up is due to old loop devices being left around after a pods is restarted. As the worker always creates a new loop devices each time it start, we can delete all loop devices on startup which should ensure that old ones are not left around.
It isn't clear why the concourse workers are sometimes failing to retire correctly after restarting. However, if we can limit the number of times the pods are restarted it should reduce the number of time we see this issue. One way of use doing this is to increase the priority of the worker pods so that they are less likely to be …
> Add priority to concourse workers and remove old loop devices

- charts/prometheus-resources/Chart.yaml
- charts/prometheus-resources/values.yaml
Remove escaping on variables as they aren't needed in this scope.
> Fix variable interpolation for 564-alert-settings

- charts/reset-user-home/templates/deployment.yaml
Make the job the main deployment instead of a post hook install.
> Remove post-install hook annotations.

- charts/jupyter-lab/files/pip-user-home.sh
- charts/jupyter-lab/templates/job-bash-profile.yaml
Currently the `pip` command is aliased so it doesn't work with Python virtual environments on the AP. Instead, a `--user` flag is set which cases `pip` to install packages under the unintuitive and not-on-the-python-path location of `.local`.
This ticket: https://trello.com/c/j3vVOQmL/624-pip-should-work-with-virtual-environments recommends `pip` on the AP should behave in the default manner, as supported by the guidance about using Python, packages and `pip` for all users of the Analytical Platform which can be found here: https://user-guidance.services.alpha.mojanalytics.xyz/tools.html#package-management and here: https://user-guidance.services.alpha.mojanalytics.xyz/tools.html#venv-and-pip
This PR removes the aliasing of the `pip` script that causes the problem behaviour.
In addition, …
> Remove aliasing of pip, so it works with virtualenv.

- charts/prometheus-resources/CHANGELOG.md
- charts/prometheus-resources/Chart.yaml
- charts/prometheus-resources/values.yaml
Add a prometheus rule that will trigger an alert if the value of kubedns_dnsmasq_errors increases.
This should allow us to detect when KubeDNS pods log errors.
(Also correct annoying spelling mistake)
> Add a Prometheus rule for KubeDNS errors

- charts/idler/CHANGELOG.md
- charts/idler/Chart.yaml
- charts/idler/values.yaml
- Maintainance release of the `idler` with updated tests dependencies
and `kubernetes` dependency (client upgraded from `v9` to `v11`).
- The above newer version had some breaking changes but these shouldn't
have any impact on the external API or behaviour of the `idler` (hence
the patch release here), see PR: https://github.com/ministryofjustice/analytics-platform-idler/pull/194
See:
- Ticket: https://trello.com/c/dYDMOvny
- Ticket: https://trello.com/c/cQCHuIDP
- Kubernetes bump PR: https://github.com/ministryofjustice/analytics-platform-idler/pull/194
**NOTE** ⚠️ : Don't merge this yet as the [`idler` PR](https://github.com/ministryofjustice/analytics-platform-idler/pull/194) is still unmerged and this rely on the release/image with this tag to be built.
> idler 2.1.1: maintainance release with libraries bumps

- charts/concourse-workers-cleaner/Chart.yaml
- charts/concourse-workers-cleaner/README.md
- charts/concourse-workers-cleaner/templates/_helpers.tpl
- charts/concourse-workers-cleaner/templates/cronjob.yml
- charts/concourse-workers-cleaner/values.yaml
Sometimes our concourse workers go into a stalled state and need to be pruned manually.
The long term fix would be to upgrade Concourse to a later version but we are likely to move away from using Concourse and the upgrade is not straightforward. Therefore this job should help reduce the number of issues we have with stalled concourse workers in the meantime.
This chart will install a CronJob object to periodically prune concourse workers that have stalled.
Based on https://github.com/luispabon/concourse-workers-cleaner
> Add concourse workers cleaner chart

- charts/limit-ranges/Chart.yaml
- charts/limit-ranges/README.md
- charts/limit-ranges/templates/limit-ranges.yaml
- charts/limit-ranges/values.yaml
If pods do not specify limits for CPU and Memory then can potentially use all the CPU and Memory on a node which can cause problems for other apps running on the same node.
We can apply Limit ranges to a namespace which will apply CPU and Memory limits and requests to containers in a pod if they don't specify them.
https://kubernetes.io/docs/concepts/policy/limit-range
> Add helm chart to apply limit ranges to kubernetes namespaces

- charts/unidler/CHANGELOG.md
- charts/unidler/Chart.yaml
- charts/unidler/values.yaml
This PR allows me to release the new version of the un-idler (see [this PR](https://github.com/ministryofjustice/analytics-platform-go-unidler/pull/16)).
> Release for unidler v 1.0.6

- charts/cpanel/CHANGELOG.md
- charts/cpanel/Chart.yaml
- charts/cpanel/templates/deployment.yaml
Using newly added `/nginx-health` endpoint in the CP nginx config to
periodically check that nginx is still alive and serving traffic.
See: https://github.com/ministryofjustice/analytics-platform-control-panel/pull/834/commits/d2e2ba33f46205b66f3060009bbc490890e52275
Part of: https://trello.com/c/eUMRw1gK
> cpanel 2.4.3: reverse-proxy container readinessProbe

- charts/cpanel/CHANGELOG.md
- charts/cpanel/Chart.yaml
- charts/cpanel/templates/deployment.yaml
Use newly added CP command to check whether a worker is still processing
background tasks at a reasonable rate or it's somehow stuck.
This is achieved by using the CP `worker_health` command (see PR below)
```
$ python3 manage.py worker_health --stale-after-secs=120
```
which will periodically submit health tasks and check if one has been
performed recently (withing 2 minutes in this case, configurable using
`----stale-after-secs=120`)
Probes are sent every 30s but note how one or more individual probes can
fail without triggering the restart of the `worker` container.
This is by design as you don't want Kubernetes to be happy-trigger and
restart this container too easily.
`successThreshold=6` means that 6 *consecutive* probes will have to fail
in order to trigger a container restart …
> cpanel 2.4.4: Added liveliness probe to `worker` (Django Channels)

- charts/cpanel/CHANGELOG.md
- charts/cpanel/Chart.yaml
- charts/cpanel/templates/deployment.yaml
Further tweaking liveliness probe for `worker` (Django Channels) container
to account for potentially very slow background tasks blocking a specific
worker.
Specifically new Deploy/Initialisation of RStudio can be VERY slow
and CP is doing a `helm upgrade --wait` so it is blocking the worker:
https://github.com/ministryofjustice/analytics-platform-control-panel/blob/main/controlpanel/frontend/consumers.py#L109-L132
The default `--timeout` for `helm` is 300s/5 minutes:
https://helm.sh/docs/helm/helm_upgrade/#options
So I'm tweaking the worker liveliness probe to consider a worker stalled when
it didn't run something for 5 minutes and reduce the chance that a worker
container is restarted just because someone installed a tool.
Part of ticket: https://trello.com/c/eUMRw1gK
> cpanel 2.4.5: tweaks to worker livelinessProbe

- charts/reset-user-home/CHANGELOG.md
- charts/reset-user-home/Chart.yaml
- charts/reset-user-home/templates/deployment.yaml
Archiving not only the `~/.conda/envs/rstudio` environment but also the
whole `~/.conda/` directory AND the `~/.condarc` config file.
This is to address RStudio startup problems caused by other conda
environments and/or broken conda configuration on JupyterLab (or whatever).
Ticket: https://trello.com/c/TWlH6wt1
> reset-user-home 0.4.2: Deeper Conda cleanup

- charts/cpanel/CHANGELOG.md
- charts/cpanel/Chart.yaml
- charts/cpanel/templates/rbac-bindings.yaml
This was referring to the old role name which is now
renamed to `cpanel-read-apps-ingresses` for consistency and
clarity.
This was causing the AP's "Manage app" page to throw an error.
(`RoleBinding` in kubernetes was fixed swiftly, this is just to be
sure helm chart is up-to-date)
> cpanel 2.4.7: Fix to read apps ingresses RoleBinding

- charts/github-actions-runner/Chart.yaml
Rollback the Helm API version to v1 for github-actions-runner
> Rollback the Helm API version to v1 for github-actions-runner 

- charts/github-actions-runner/Chart.yaml
- charts/github-actions-runner/org_runner.yaml
- charts/github-actions-runner/repo_runner.yaml
- charts/github-actions-runner/templates/deployment.yaml
- charts/github-actions-runner/values.yaml
- Adds org_runner and repo_runner example configuration
- Namespace the runner now we also have dind configuration
- Make the dockerhost configurable
- Make the Docker image configurable
- Make runner groups configurable
Adding org_runner and repo_runner configuration make it easier to test the logic in the deployment.yaml
Namespacing the runner values makes the hierarchy easier to understand for new users, and clarifies the shared values i.e. the values that are not under either the dind or runner key.
Making the DIND container image configurable makes it easy to update the Docker version without needing to update the Helm chart every time.
We can now configure runners to register with a specified runner group.
https://trello.com/c/ZNtuRljD/819-github-actions-runner
Run
```shell
helm …
```
> Tidy the runner configuration

- charts/github-actions-runner/Chart.yaml
- charts/github-actions-runner/templates/deployment.yaml
Fixes the error:
Status: invalid argument "\"tcp://0.0.0.0:276\"" for "-H, --host" flag: Invalid bind address format: "tcp://0.0.0.0:2376"
> Stop quoting the docker host variable

- charts/webapp/CHANGELOG.md
- charts/webapp/Chart.yaml
- charts/webapp/values.yaml
It's the same image used before and same tag also but it's hosted on
our AWS ECR repository so that we don't hit the DockerHub rate limits.
> webapp 2.3.11: pull fluent-bit image from AWS ECR

- charts/fluentd/Chart.yaml
- charts/fluentd/values.yaml
Set maximum log retries to be 10 - default is 17 (bit random?), but this has caused problems with queued logs overwhelming the Elastic.co ingress nodes
Fixes:
https://trello.com/c/79iOACmg/845-define-reasonable-retry-limit-for-logs-and-apply-it-via-chart
https://trello.com/c/SnaBMHdz/840-turn-off-healthz-reporting-for-k8s-pods
> Silently drop all kube-probe requests

- charts/images-prepuller/Chart.yaml
- charts/images-prepuller/templates/deamonset.yaml
Pull init container for prepull pods from ECR. Reducing number of images we need to pull from Docker Hub.
> Pull init container for prepull pods from ECR

- charts/reset-user-home/templates/deployment.yaml
* Use `mv -f` to force the rename.
* I've removed the superfluous `rm -rf` of the path that's just been `mv`-ed.
* No idea how to test this. #helmnewbie ;-)
Please feel free to ignore.
Related Trello card: https://trello.com/c/eEmNEwI7/830-make-home-reset-faster
> Use mv rather than copy to backup old directories when resetting user's home

- charts/reset-user-home/CHANGELOG.md
- charts/reset-user-home/Chart.yaml
- charts/reset-user-home/templates/job.yaml
This was causing the job to mysteriously fail.
Also:
- bumped patch number in version and updated Changelog (also with details
about previous changes to chart)
- renamed `deployment.yaml` template file to `job.yaml` as this contains
a kubernetes `Job` resource (not a `Deployment`)
> rest-user-home 0.4.3: Fix job failing because of semicolons

- charts/jupyter-lab/CHANGELOG.md
- charts/jupyter-lab/Chart.yaml
- charts/jupyter-lab/templates/deployment.yaml
- charts/jupyter-lab/values.yaml
Why?
----
- use `allspark` flavour of JupyterLab image means more users can use Spark
when needed
- move a user to `allspark` flavour is currently a manual and error-prone
process (although documented in our [wiki])
- reduced fragementation and potential retirement of one of the current three
flavours of JupyterLab images
Potential drawbacks
-------------------
- image sizes concerns seem to not be a problem especially after updating
`allspark`'s BASE image. `allspark-notebook:v1.1.0` is ~2.7GB which is
smaller than `datascience-notebook:v0.6.9` previosly used which
was ~4.4GB
- above would be mitigated anyway by the fact this Docker image is now
pulled from the AWS ECR registry and not quay.io which should be faster
- potential unexpected breaking changes caused by a different Docker …
> jupyter-lab 1.0.0: Spark image is now default

- charts/rstudio/CHANGELOG.md
- charts/rstudio/Chart.yaml
- charts/rstudio/templates/deployment.yml
We are using an init container as it will always finish no matter how long it takes.
Some user homes take a long time to chown as they contain a lot of conda packages.
We don't mind which group the home files are in as they can be both `users` and `staff` depending on which tool created it.
> [ANPL-239] RStudio: Add an init container to change the user home on boot

- charts/concourse-org-pipeline/CHANGELOG.md
- charts/concourse-org-pipeline/Chart.yaml
- charts/concourse-org-pipeline/templates/secrets.yaml
- charts/concourse-org-pipeline/values.yaml
- Added IP range secrets for mojo network to concourse org pipeline chart for use in webapp deployment IP restriction parameters.
- Add maintainer and missing value to keep chart linting happy
> ANPL-369 Add secret for mojo network

- .gitignore
- charts/rstudio/CHANGELOG.md
- charts/rstudio/Chart.yaml
- charts/rstudio/templates/deployment.yml
- charts/rstudio/values.yaml
So this doesn't work. I'm not sure why, although I have some ideas.
1) This helm chart is based on the continuing work that Dan did. I'm not sure if his changes to the helm chart will work with the new work on the docker images I did.
2) I'm just running the wrong sort of commands when trying to test `helm`... 
```
$ helm upgrade --install --wait --force rstudio-ntoll rstudio --version 3.1.3 --namespace user-ntoll --values rstudio/values.yaml --set proxy.auth0.domain=alpha-analytics-moj.eu.auth0.com --set proxy.auth0.clientId=$AUTH0_CLIENT_ID --set proxy.auth0.clientSecret=$AUTH0_CLIENT_SECRET
Release "rstudio-ntoll" does not exist. Installing it now.
Error: release rstudio-ntoll failed: timed out waiting for the condition
```
3) Nicholas does devops is like Godzilla does needlework. ;-)
> WiP - surely I just needed to update the versions..?

- charts/cpanel/CHANGELOG.md
- charts/cpanel/Chart.yaml
- charts/cpanel/README.md
- charts/cpanel/templates/frontend-deployment.yaml
- charts/cpanel/templates/ingress.yaml
- charts/cpanel/templates/secrets.yaml
- charts/cpanel/templates/worker-deployment.yaml
- charts/cpanel/values.yaml
When we move to EKS we would like to avoid having to create Kubernetes secrets with Helm charts, as this requires us to provide secret values, in the clear as inputs to helm charts.
Instead we would like to have the option of creating the Kubernetes secrets from values stored in AWS secrets manager.
This change allows us to disable to create of Kubernetes secrets for in the control panel helm chart by setting a secrets.create to false.
By default all Kubernetes secrets will continue to be created as in previous versions of the chart.
> ANPL-400 Add option to disable secret creation in the control panel helm chart

- charts/rstudio/CHANGELOG.md
- charts/rstudio/Chart.yaml
- charts/rstudio/values.yaml
Update RStudio helm chart to use the nginx proxy image with a configurable redirect url
> ANPL-479 - Update RStudio helm chart to use nginx proxy image with configurable redirect url

- charts/rstudio/CHANGELOG.md
- charts/rstudio/Chart.yaml
- charts/rstudio/templates/configmap-renviron.yaml
- charts/rstudio/templates/deployment.yml
- charts/rstudio/values.yaml
In order for RStudio users to be able to access AWS resources from RStudio, they need to be able to get AWS credentials by assuming their IAM role.
- For users running on EKS we will grant AWS access using IAM for Service Accounts.
- For users running on the legacy (kops) clusters, we will continue to use use kube2iam to grant AWS access.
RStudio sessions run under a different user from the RStudio container (which runs as root).
This means that for users running on EKS we need to set the  AWS_ROLE_ARN and AWS_WEB_IDENTITY_TOKEN_FILE environment variables for the R Studio session.
This can be done in a few different way, but the more flexible will be to mount a .Renviron file in the root of a users home directory . This will will contain the AWS_ROLE_ARN and AWS_WEB_IDENTITY_TOKEN_FILE …
> ANPL-498 Add Renviron configmap to Rstudio chart
